### ISSUE TITLE
Umzug should reject a migration if it can't find the migration method

### ISSUE THREAD

**Issue by aboveyou00** [sequelize/umzug#122]
Note: I created a pull request for this a while back, but it hasn't been merged in yet. I'm not sure what the process is supposed to be, so I created an issue. This is the pull request:

#115 

Rationale for change: you will never have a no-op migration. Currently, if the up or down methods can't be found when running a migration, Umzug replaces the method body with Promise.resolve() and tells you that the migration was run correctly. (It wasn't.)

**Comment by jukkah** [comment]
No problem, there is no official process as this project is very small and don't have an active maintainer (as I have been busy for a while).
