### ISSUE TITLE
Questions about migrations

### ISSUE THREAD

**Issue by overlookmotel** [sequelize/umzug#13]
Hi all.

This module looks great. Up until now I've been doing migrations by hand but with multiple servers running the same sequelize-based app, it's becoming a real pain.

A couple of questions:

1. Are there examples anywhere of migration files for common sequelize migrations e.g. adding a column to a table?

2. Is there a way to specify in migration files in what order they should be run (e.g. migration X must run after migration Y)?

What I'm thinking with (2) is that it'd be nice to specify dependencies in the migration files themselves so then you can just run `umzug.up()` without options, and know they'll run in the right order. Or is the solution to number the migration files to ensure correct order of execution?

Hope you can help...

**Comment by mraxus** [comment]
Hi @sdepold and @mickhansen.

Could you please redirect to another documentation which define QueryInterface functions as the link @sdepold provided now redirects to http://sequelize.readthedocs.org/en/latest/#functions which does not contain any functions at all.

Best Marcus

**Comment by sdepold** [comment]
There you go :) https://sequelize.readthedocs.org/en/latest/docs/migrations/#functions

**Comment by mraxus** [comment]
@sdepold You're an angel. Thanks =)

**Comment by sdepold** [comment]
May I point you to this comment? https://github.com/sequelize/cli/issues/75#issuecomment-68154955 Please let me know if that makes thing more clear

**Comment by mraxus** [comment]
I think I have understood how it works now. Thanks!

I created a repo to have as an example of how to best programmatically use sequelize migrations. Please feel free to add comments for improving and better understanding how to use migrations in the optimal way. Use it as an example in your own documentation should it be acceptable as an example.

https://github.com/mraxus/seq-mig
