### ISSUE TITLE
Minifying code gives an error

### ISSUE THREAD

**Issue by dtslvr** [sequelize/umzug#141]
Hi,

when I try to minify my project including umzug I get the following error: `Unexpected token: punc ([)`

My investigation has shown that this line is the reason: [SequelizeStorage.js Line 77](https://github.com/sequelize/umzug/blob/f8b9b453e60c4ae7382026a5b85786d5c9e989ec/src/storages/SequelizeStorage.js#L77). Any chance to get it fixed?

Thanks and kind regards,
Thomas

**Comment by dtslvr** [comment]
Thanks for your reply. I'm using the latest version (2.0.1) in my private project.

I've just compared the two files:

`node_modules/umzug/src/storages/sequelize.js`
```
  ...
  getModel() {
    ...
    return this.sequelize.define(
      this.modelName,
      {
        [this.columnName]: {
          type: this.columnType,
          allowNull: false,
          unique: true,
          primaryKey: true,
          autoIncrement: false
        },
      }
      ...
    );
  }
  ...
```


`node_modules/umzug/lib/storages/sequelize.js`
```
  ...
  (0, _createClass3.default)(SequelizeStorage, [{
    key: 'getModel',
    value: function getModel() {
      ...
      return this.sequelize.define(this.modelName, {
        [this.columnName]: {
          type: this.columnType,
          allowNull: false,
          unique: true,
          primaryKey: true,
          autoIncrement: false
        }
      }
      ...
  }
  ...
```

Do you think the transpilation is not working correctly? I see ``[this.columnName]`` in both files.

**Comment by jukkah** [comment]
Oh, something must be broken in our babel config as this is a new feature in the language and it should be transpiled in lib.

**Comment by jukkah** [comment]
It seems, your minifier doesn't understand these correctly. Are you hopefully using Uglify?

**Comment by dtslvr** [comment]
Yes, you are absolutely right. Thanks for your support :)
I'm now using UglifyJS2 which supports ES6.
