### ISSUE TITLE
Example of custom storage

### ISSUE THREAD

**Issue by OmisNomis** [sequelize/umzug#143]
I'm currently trying to write a custom storage option for Mongoose, but it's proving quite difficult. Do you have some examples you could share on how to achieve this?

I've looked through the built in storage options and the documentation and it hasn't made it clear.

**Comment by chadxz** [comment]
Does this help? https://github.com/sheerun/knex-migrate/blob/master/src/storage.js

**Comment by sushantdhiman** [comment]
Related documentation https://github.com/sequelize/umzug#custom
