### ISSUE TITLE
Greedy lock on the migrations table

### ISSUE THREAD

**Issue by gvko** [sequelize/umzug#144]
Does Umzug or Sequelize do a lock on the migrations table (the table in which the executed migrations are stored, f.e. `SequelizeMeta`) before the migrations are to be executed and until they are finished?

If so, is it a greedy (no read/write possibilities) or a lazy lock?

I went through both the Umzug and Sequelize Migrations documentation and could not find information about that.

**Comment by jukkah** [comment]
No, currently it's not locking the table at all.

**Comment by caseyduquettesc** [comment]
Would help with #59

**Comment by jaulz** [comment]
Any chance to implement it? Are you willing to accept a PR?

**Comment by atorma** [comment]
I've used this: https://github.com/SGrondin/umzug-sync
