### ISSUE TITLE
Maintainer needed

### ISSUE THREAD

**Issue by jukkah** [sequelize/umzug#145]
I don't have enough free time to maintain this project so I'm asking your help. You will be the main maintainer and I'll help you when you ever need some help. If you got interested, please comment bellow or contact me (@jukkah) on [Sequelize's Slack](https://sequelize.slack.com).

**Comment by chakrihacker** [comment]
Hi @jukkah , I am interested

**Comment by jukkah** [comment]
@chakrihacker Great. You don't have any previous experience with Umzug so please send a PR with any kind of improvement first so that I can review you with other Sequelize members.

**Comment by chakrihacker** [comment]
Give me 2 to 3 days, I will make it

**Comment by PascalPflaum** [comment]
I offer my help as well. I'm using umzug in some projects and would like to keep it alive.

**Comment by jukkah** [comment]
Cool

**Comment by jukkah** [comment]
@PascalPflaum I've made you an admin. Feel free to take control of this project. In addition, please join to [slack](https://sequelize.slack.com) (if you are not there already) so that I can add you to maintainers group.

**Comment by PascalPflaum** [comment]
@jukkah 
The Workspace is invite only.

> Don't have an account on this workspace yet?
> Contact the workspace administrator for an invitation

**Comment by jukkah** [comment]
Ah, try this http://sequelize-slack.herokuapp.com/

**Comment by PascalPflaum** [comment]
Thanks I joined and pinged you at slack.

**Comment by broofa** [comment]
Update README.md to remove the [kinda scary] "maintainers needed" callout?
