### ISSUE TITLE
Gulp lint target not running

### ISSUE THREAD

**Issue by PascalPflaum** [sequelize/umzug#146]
I'm writing a MongoDB Storage (https://github.com/PascalPflaum/umzug/tree/feature/MongoDBStorage) right now and noticed that the gulp lint target is not working with the current code. 

>
src/index.js
  line 53  col 7   Expected '}' to match '{' from line 47 and instead saw '...'.
  line 53  col 10  Missing semicolon.
  line 54  col 5   Unexpected '}'.
  line 53  col 17  Expected an assignment or function call and instead saw an expression.
  line 53  col 18  Missing semicolon.
  line 54  col 6   Unnecessary semicolon.
  line 56  col 9   Expected an identifier and instead saw 'this' (a reserved word).
  line 56  col 13  Expected ')' to match '(' from line 56 and instead saw '.'.
  line 56  col 13  'function closure expressions' is only available in Mozilla JavaScript extensions (use moz option).
  line 56  col 68  Unexpected ')'.
  line 56  col 70  Unexpected '{'.
  line 57  col 13  Class properties must be methods. Expected '(' but instead saw 'new'.
  line 57  col 23  Expected an identifier and instead saw 'The logging-option should be either a function or false'.
  line 57  col 80  'function closure expressions' is only available in Mozilla JavaScript extensions (use moz option).
  line 57  col 81  Expected an identifier and instead saw ';'.
  line 58  col 6   Missing semicolon.
  line 64  col 23  Missing "use strict" statement.
  line 65  col 7   Expected '}' to match '{' from line 60 and instead saw '...'.
  line 65  col 10  Missing semicolon.
  line 66  col 5   Unexpected '}'.
  line 65  col 33  Expected an assignment or function call and instead saw an expression.
  line 65  col 34  Missing semicolon.
  line 65  col 33  Unrecoverable syntax error. (10% scanned).

  ✖  12 errors
  ⚠  11 warnings

If you need help fixing this issues, I would do so in a seperate branch.

**Comment by PascalPflaum** [comment]
I suggest to switch to eslint instead eshint. Eshint doesn't support ES7 and spread operator not yet AFAIK.

**Comment by jukkah** [comment]
PR is more than welcome +1

**Comment by PascalPflaum** [comment]
adressed in #148
