### ISSUE TITLE
Generating raw SQL migration query files

### ISSUE THREAD

**Issue by borislemke** [sequelize/umzug#150]
In rails, generating migrations will also generate an `.sql` file to be used with SQL.
E.g, when creating a new migration, it will be accompanied with something like this file:
`2103232813.sql`
```
ALTER TABLE `products` CHANGE `group` `group` varchar(50) DEFAULT NULL
ALTER TABLE `products` CHANGE `person` `person` varchar(50) DEFAULT NULL
ALTER TABLE `products` CHANGE `store_name` `store_name` varchar(50) DEFAULT NULL
```

Is this possible with `sequelize` / `umzug` as well? At our company, engineers do not have access to production servers so we usually give the raw queries to our devops which they use to execute migrations on our production database.

I was thinking that this would be possible by using a custom storage adapter in `new Umzug({storage: CustomStorage})`? I would appreciate if someone could guide me to the right direction to achieve this functionality.

**Comment by PascalPflaum** [comment]
Hi.

The storage parameter just defines the space where umzug stores which migration is already executed and which not.

Right now umzug does not accept pure sql files, but there is a PR #149 that will allow this, when merged.

**Comment by borislemke** [comment]
Hi @PascalPflaum, thanks for the reply.
In the issue you referenced, it refers to some query operations like `find` or `all`. What I would like to see is when running a migration, the raw query that is used by sequelize / umzug to be dumped into an `.sql` file. Did you by any chance took a look into rails? They have great support for this feature.

**Comment by PascalPflaum** [comment]
Hi @borislemke,
indeed I see this feature useful as well. "Umzug" is database agnostic and transforming a migration into database language is up to the ODM / Database Driver. I think sequelize would be the right project to open a issue in your case.
