### ISSUE TITLE
Support for multiple migrations paths in Umzug options

### ISSUE THREAD

**Issue by nskondratev** [sequelize/umzug#151]
Hello, is there any possibility to define multiple directories in Umzug migration.path option?
For example:
```js
const umzug = new Umzug({
  migrations: {
    path: ['./dir1', './dir2'],
  }
})
```
I see that there is one rejected PR which implements this feature.

**Comment by PascalPflaum** [comment]
No, there is no option yet.
I will try to get the mentioned PR #106 in the codebase soon.

**Comment by mbonig** [comment]
or perhaps a globbed path

**Comment by tamlyn** [comment]
Or an array of globs? 😀

**Comment by jedwards1211** [comment]
The node `glob` package is so easy to use, to me it would be convenient enough if I could just pass glob and pass in whatever array of files I want.

**Comment by sarangnx** [comment]
Kind of a workaround is to put the ./dir1 and ./dir2 in the same folder and set `traverseDirectory` flag to true. 
In case you want to select a subset of the migrations, put some suffix like `.dir1.js` to the migration file and use regex patterns to load the migrations.

**Comment by mmkal** [comment]
Migrations are specified using `glob` in v3 so this is now supported. See https://github.com/sequelize/umzug#migrations. Docs include how to specify multiple folders.
