### ISSUE TITLE
custom sorting function

### ISSUE THREAD

**Issue by dwelle** [sequelize/umzug#153]
Umzug sorts migration filenames by name, thus files named `1`, `2`, `12` will be sorted `1`, `12`, `2`. Files can also be named using different paterns (`major.minor` etc.), so it's best to allow to supply custom sorting function.

**Comment by dwelle** [comment]
Hmmm.. I thought umzug sorts the migrations on its own, but I had to add a manual `ORDER BY` when fetching executed migrations that are returned from the custom `executed` callback. I would note that in the docs, if that's really the case (?). I can make a PR.

**Comment by cesarvarela** [comment]
I wonder how do you guys name the migrations, without being affected by this

**Comment by dwelle** [comment]
We're using epoch timestamp. After that, you can add any string you want: `<timestamp>-<name>`

**Comment by ALiangLiang** [comment]
So what is going on now?
https://github.com/sequelize/umzug/blob/ebb08d65d5365a77d54b68eb87e2cc1249cb727a/src/index.js#L457

**Comment by papb** [comment]
[Released at v3.0.0-beta.4](https://github.com/sequelize/umzug/releases/tag/v3.0.0-beta.4)!
