### ISSUE TITLE
Support for coffeescript 2

### ISSUE THREAD

**Issue by mdarveau** [sequelize/umzug#159]
Coffeescript 2 changed the import from `coffee-script` to `coffeescript`.

I made a pull request to support both: https://github.com/sequelize/umzug/pull/158

**Comment by mdarveau** [comment]
Hi! Could you do a new release with this PR?

Thanks

**Comment by mmkal** [comment]
This is released as of v2.2.0. However the plan is to drop built-in coffeescript support - to use it in v3 you'll need a custom resolver.
