### ISSUE TITLE
Specifying migration name should not fail if migration has already been run

### ISSUE THREAD

**Issue by chadxz** [sequelize/umzug#167]
I opened [a ticket](https://github.com/sheerun/knex-migrate/issues/18) on knex-migrate issue tracker, but after investigating, I feel this issue is really more about umzug.

When
1. doing an "up" migration
2. the migration name is specified
3. and the migration has already run

currently the library rejects the migration with the message: "Migration is not pending: %migration_name%".

I contend that this would be better as a success state. If I want a given migration to be run and it has already been run, then... mission accomplished? I think if this were the case, we could print "Migration already applied" and exit with a success status.

What do you think?

**Comment by chadxz** [comment]
I'd be happy to submit a PR along these lines if this is something you'd be open to having changed.

**Comment by asnaseer-resilient** [comment]
I am suffering from the same error and totally agree with your thoughts on this @chadxz 

Is anyone looking into how to fix this at all?

**Comment by mmkal** [comment]
Yes we're discussing this. Existing flows might be depending on the current behaviour, making this a breaking change. So any update will be in v3, which isn't finalised yet. We can use this issue to discuss what the behaviour should be. As I see it there are three options, when an already-run migration is explicitly requested:

1. Throw
2. No-op
3. Run again

It sounds like the request here is 2. Is that right?

**Comment by asnaseer-resilient** [comment]
@mmkal Yes, option 2 would be preferable. You could add an option to control this behaviour to avoid breaking any existing code that relied on the old behaviour - e.g.:

```
await umzug.up({ to: '20141101203500-task', alreadyAppliedBehaviour: Behaviour.NOOP });
```
where the default value would be `Behaviour.THROW`.

**Comment by chadxz** [comment]
FWIW, my use case was this: I needed to run a single migration, then run some custom logic, then run the remainder of the migrations. I was able to work around the issue in this ticket with this:

I created a npm run script with the following:

```
knex-migrate list | grep -q '20180315084901_needed_migration_name' && echo 'YES' || echo 'NO'
```

Then checked the output of that command to determine whether it should run or not.

> It sounds like the request here is 2. Is that right?

To me that would be the least surprising thing, which is always good 👍

**Comment by papb** [comment]
Hi @asnaseer-resilient and @chadxz, I think it is a good idea to have this configurable, and the default choice could be the one such that no breaking change happens.

@mmkal what do you think?
