### ISSUE TITLE
How to run only up sql scripts

### ISSUE THREAD

**Issue by swamy526** [sequelize/umzug#173]
For Example,
I have 2 files like

1_test.up.sql
2_test.down.sql

in migrations folder.

Now, When I executed command "node migrate up",
umzug executing both up and down SQL scripts.

To resolve above issue, I added a custom resolver like below

```javascript
{
        up:  function(){
                if(path.endsWith('up.sql'))
                    sequelizeInstance.query(fs.readFileSync(path, 'utf-8'));
            },
            down:  function(){
                if(path.endsWith('down.sql'))
                    sequelizeInstance.query(fs.readFileSync(path, 'utf-8'));
            }
}
```

But Still, In migrations table, umzug writing above 2 file  names as executed, even though only up sql script ran by it.

**Comment by jonaskirkemyr** [comment]
Did you ever resolve your issue?

How about creating a regex for your _up_  `.sql` files? 

I would pass in a regex to migrations options like: 
```
{
    pattern: /\d_.*\.up\.sql$/,
    customResolver: path => {
        const downPath = path.replace('up', 'down');
        return ({
            up: () => sequelizeInstance.query(fs.readFileSync(path, 'utf-8')),
            down: () => sequelizeInstance.query(fs.readFileSync(downPath, 'utf-8'));
        });
    }
}
```

The regex would match `DIGIT_NAME.up.sql` and umzug would only run migrations for filenames matching the regex.

**Comment by mmkal** [comment]
@jonaskirkemyr's solution should work; closing.
