### ISSUE TITLE
up/down "to" migration should be exclusive

### ISSUE THREAD

**Issue by dwelle** [sequelize/umzug#175]
From an [English semantic viewpoint](https://english.stackexchange.com/a/178777/91722), when you run `umzug.down({ to: "2" })`, then it should not run `down` migration of task `2`.

Similarly, `umzug.up({ to: "2" })` should not run `up` migration of task `2`.

**Comment by dwelle** [comment]
After debating with the team, it seems that no one cares about what English cares about. So, I'll just update docs.

Still, uzmug's `from` is _exclusive_, which seems a bit inconsistent.

**Comment by eyelidlessness** [comment]
This decision is extraordinarily disappointing. The behavior is wildly inconsistent with the wording in usage, and causes completely unexpected behavior.
