### ISSUE TITLE
Ignoring sourcemaps

### ISSUE THREAD

**Issue by dorrotman** [sequelize/umzug#182]
Hello,

I am using TypeScript, and the compiler generates sourcemap files alongside all javascript files.
Taking into consideration this commit: https://github.com/sequelize/umzug/commit/890e5e16983fa52a258740d0c5246bc97a58d432
This causes warnings to be logged for each sourcemap file:
````
File: ....js.map does not match pattern: ...
````
The commit description says:

> If there is other files, the pattern is probably filtering out some migrations.

However, in my opinion, sourcemaps are very common and should be allowed to exist alongside the javascript files. Come to think of it, the reason I use a filter is **because** I have other files and want to ignore them.

I would like to come up with a solution for this.
Possible solutions:

1. Ignoring sourcemap files before trying testing the `pattern` matching
2. Adding a `suppressWarnings` flag to the configuration so that it will not be logged
 

What do you think is the best solution?

Thanks!

**Comment by ephemer** [comment]
> Come to think of it, the reason I use a filter is because I have other files and want to ignore them.

this.

Can we please get rid of these logs entirely?

**Comment by po5i** [comment]
I'll be working on improving this verbosity level, I'm thinking of adding the new option, and probably a companion PR to sequelize-cli as well.

**Comment by sonicdoe** [comment]
With https://github.com/sequelize/umzug/commit/cdfd53ee52bd7d9a64a6d0f11cb4c76f2ad3c6d3, non-migration files are no longer logged at all, so I think this issue can be closed.

**Comment by sushantdhiman** [comment]
This should be fixed with `2.3.0` release
