### ISSUE TITLE
Array of Migration instances?

### ISSUE THREAD

**Issue by rchamberlin** [sequelize/umzug#184]
Is there an example of passing an array of migration instances to the configuration object?  I see in the documentation:

`// (advanced) you can pass an array of Migration instances instead of the options below`

but I'm not sure how that would work.  I've tried:

```
const migrations = [
  { up: function () { ... }, down: function () { ... }
]

const umzug = new Umzug({
  ...,
  migrations: migrations
})
```

but that doesn't seem to be correct.

**Comment by Lax** [comment]
It should be an array of `Migration` instances

```
const migrations = [
  new Migration('./migrations/....js', {...}),
  new Migration('./migrations/....js', {...})
]
```

however the `Migration` class is not exported, I cannot get an reference to `Migration` class

**Comment by eldarshamukhamedov** [comment]
You can get to it with `import Migration from 'umzug/lib/migration'`, but I wouldn't rely on either the path or the interface to be safe in the long term. Would be :100: to have the class exported and officially added to the library API.

**Comment by eldarshamukhamedov** [comment]
@arnaubennassar sort of. I think we're trying to do slightly different things, but I'll post my progress anyway.

Umzug assumes that you keep your migrations in separate files which it imports for you when you use it. In my case, there is no file system to store migration files on. Instead, I bundle them with the rest of my application source. Umzug is not built with this in mind, but I ended up writing a factory function that creates Umzug-compatible migration objects:

```js
/**
 * @param {postgres.Pool} pool Database connection pool
 * @param {String} key Unique ID for a migration (Ex. 20181217000005-create-table)
 * @param {Function} up Up migration function
 * @param {Function} down Down migration function
 */
export function createMigration(pool, { key, up, down }) {
  // Make sure all of the expected functions exist
  if ([up, down].some(fn => typeof fn !== 'function') || !key) {
    throw new Error(
      `Failed to create migration object (${key}).`,
      `Missing one of the required migration params: up, down, key.`,
    );
  }

  // This is the API Umzug expects
  return {
    path: null, // bypass Umzug import
    file: key, // unique migration ID
    up: () => up(pool), // migrate up
    down: () => down(pool), // revert down
    testFileName: needle => key.startsWith(needle), // name filter used by Umzug to decide if it should run this migration
  };
}
```

Note that `up(pool)` and `down(pool`) is how I'm passing the arguments to the migration function. If you're using Sequelize, you can hook it up here. I'm using a raw `pg.Pool` instance without Sequelize.

Now I can create migrations manually like this:

```js
import pg from 'pg'

const migration = {
  key: "20181217000005-create-table",
  up: db =>
    db.query(`
        CREATE TABLE IF NOT EXISTS "files" (
          "file_id" UUID NOT NULL UNIQUE DEFAULT uuid_generate_v4() PRIMARY KEY,
          "filename" VARCHAR,
        );
      `),

  down: db => db.query('DROP TABLE IF EXISTS "files" CASCADE')
};

// Pass migrations to Umzug
new Umzug({
  storage: { ... },
  storageClass: { ... },
  migrations: [createMigration(pool, migration)]
});
```

Hope that helps, even if it's not exactly what you are looking for. Usual word of caution: Umzug might change their API and break this in the future.

**Comment by arnaubennassar** [comment]
@eldarshamukhamedov Thanks for your quick reply! I've managed to move the migration files into a folder where I could actually access them. So I will take your advice and do it by absolute path.

**Comment by jedwards1211** [comment]
@rchamberlin you can blame me for this, in my PR to support passing an array of migrations I forgot to update the docs.

**Comment by jedwards1211** [comment]
FWIW, I think having a `Migration` class is not the ideal design to begin with, it would be simplier if one could just pass an array of `{ name: string, up: () => Promise<any>, down: () => Promise<any> }` objects.  The `Umzug` class can handle loading the migrations from `options.migrations.path`, `options.migrations.pattern`, `options.migrations.wrap`, and `options.migrations.customResolver`, and supporting CoffeeScript...or that functionality could be moved into a `createMigration` function that just creates a POJO.

**Comment by AleskiWeb** [comment]
Any movement on this? Using webpack with Umzug is extremely annoying if I have to write my own handler to resolve the migrations, instead of just providing a `require`d array of them

**Comment by nicolas-van** [comment]
I opened a pull request to make it easy to specify a list of migrations without using a file loader: https://github.com/sequelize/umzug/pull/199 . This approach works flawlessly with Webpack.

In the mean time you can just take a look at the code of this PR and copy the `migrationsList()` function in your code. That's what I currently do in my project using umzug with webpack.

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/umzug/pull/199
