### ISSUE TITLE
migration return array failed to execute

### ISSUE THREAD

**Issue by greatghoul** [sequelize/umzug#185]
## error details

```
== 20180828102922-add-sponsor-intro-to-lotteries: migrating =======

ERROR: Error: Migration 20180828102922-add-sponsor-intro-to-lotteries.js (or wrapper) didn't return a promise
    at /Users/greatghoul/Workspace/Miidii/Sweetfoot/node_modules/umzug/lib/migration.js:132:15
    at Generator.next (<anonymous>)
    at step (/Users/greatghoul/Workspace/Miidii/Sweetfoot/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/greatghoul/Workspace/Miidii/Sweetfoot/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

## migration file

```
'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return [
      queryInterface.addColumn('Lotteries', 'sponsor_intro', {
        type: Sequelize.TEXT,
        allowNull: true,
      }),
      queryInterface.addColumn('Lotteries', 'prefs', {
        type: Sequelize.JSONB,
        allowNull: false,
        defaultValue: {},
      }),
      queryInterface.addColumn('Lotteries', 'award_usage', {
        type: Sequelize.TEXT,
        allowNull: true,
      }),
      queryInterface.addColumn('Lotteries', 'award_price', {
        type: Sequelize.STRING,
        allowNull: true,
      }),
    ];
  },

  down: (queryInterface, Sequelize) => {
    return [
      queryInterface.removeColumn('Lotteries', 'sponsor_intro'),
      queryInterface.removeColumn('Lotteries', 'prefs'),
      queryInterface.removeColumn('Lotteries', 'award_usage'),
      queryInterface.removeColumn('Lotteries', 'award_price'),
    ];
  }
};
```

**Comment by Lax** [comment]
I guess it should be using Promise instead of Array.

```
return queryInterface.addColumn(...)
             .then(() => {
               return queryInterface.addColumn(...)
             })
             .then(...)
```

**Comment by greatghoul** [comment]
promise style always works, but array style is now broken.

**Comment by akenger** [comment]
Ran into this today as well...

**Comment by spathon** [comment]
Was an easy fix for me to just change `return [` to `return Promise.all([` and ending `])`

**Comment by greatghoul** [comment]
I locked umzug to `2.1.0`.

```
{
  "dependencies": {
    ...
    "umzug": "2.1.0",
    ...
  }
}
```

**Comment by samathan** [comment]
Hi,

Below is my migration script,
'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return
   queryInterface.addColumn( 'tablename', 'columnname1', Sequelize.BLOB)
   .then(() => {
   return queryInterface.addColumn( 'tablename', 'columnname2', Sequelize.STRING);
 })
  },

  down: (queryInterface, Sequelize) => {
    return
   queryInterface.removeColumn( 'tablename1', 'columnname1' )
   .then(() => {
   return queryInterface.removeColumn( 'tablename1', 'columnname2' );
 });
}
}
 Below error while executing the above migration ,
== 20181203091310-nameassets-addcolumns: migrating =======

ERROR: Migration 20181203091310-nameassets-addcolumns.js (or wrapper) didn't return a promise

Can some help me with this?
Thank you.

**Comment by greatghoul** [comment]
```
'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return // <---- it returns here, code below this line not executed.
    queryInterface.addColumn('tablename', 'columnname1', Sequelize.BLOB)
      .then(() => {
        return queryInterface.addColumn('tablename', 'columnname2', Sequelize.STRING);
      })
  },

  down: (queryInterface, Sequelize) => {
    return
    queryInterface.removeColumn('tablename1', 'columnname1')
      .then(() => {
        return queryInterface.removeColumn('tablename1', 'columnname2');
      });
  }
}
```

@samathan you should change it to 

```
'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.addColumn('tablename', 'columnname1', Sequelize.BLOB)
      .then(() => {
        return queryInterface.addColumn('tablename', 'columnname2', Sequelize.STRING);
      })
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.removeColumn('tablename1', 'columnname1')
      .then(() => {
        return queryInterface.removeColumn('tablename1', 'columnname2');
      });
  }
}
```

**Comment by Ricardonacif** [comment]
Question is: do we wanna keep the array support or are we dropping it?

**Comment by greatghoul** [comment]
I vote for the array support.

**Comment by toddpla** [comment]
After reinstalling version `sequelize 4.36.1` & `sequelize-cli 4.0.0` then running migrations locally I came across this issue. It would be useful to know whether there is a way to revert back to how it was before this change was implemented. Are there any release notes on this?

**Comment by thutv18** [comment]
Hi @toddpla ,

I've tried re-install the sequelize. It still does not work.
This is error:
![image](https://user-images.githubusercontent.com/45755368/58366658-c5b14480-7eff-11e9-8464-a21fb30563c7.png)
This is my migration:
![image](https://user-images.githubusercontent.com/45755368/58366662-de215f00-7eff-11e9-97cf-742ce755baee.png)

**Comment by spathon** [comment]
@thutv18 You could easily fix your migration by wrapping it in a `Promise.all`
Eg `return Promise.all([ queryInterface.addColumn ... ])`

**Comment by thutv18** [comment]
Thank @spathon ,
I knew this solution. But, i'm working on the existed database with many files migration. So the effort to update all files is very much.
However, I found other solution for this case. Using "node_modules/.bin/sequelize db:migrate" to run. It works for me

**Comment by enbermudas** [comment]
I'm using version `^5.21.5` and this issues is happening to me while executing the `db:seed:undo:all` command.

The `Promise.all([...])` ain't working for me:

```
module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.createTable('Elements', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER,
      },
      name: {
        allowNull: false,
        type: Sequelize.STRING,
      },
      description: {
        allowNull: false,
        type: Sequelize.TEXT,
      },
      createdAt: {
        allowNull: false,
        type: Sequelize.DATE,
      },
      updatedAt: {
        allowNull: false,
        type: Sequelize.DATE,
      },
    });
  },
  down: queryInterface => {
    return Promise.all([queryInterface.dropTable('Elements')]);
  },
};
```

**Comment by enbermudas** [comment]
This error is happening to me while using the `db:seed:undo:all` command. The `Promise.all([...])` solution is not working either.

Sequelize version: `^5.21.5`

Current code:

```
const baseRecord = {
  description: 'Description...',
  createdAt: new Date(),
  updatedAt: new Date(),
};

const records = ['Fire', 'Water', 'Earth', 'Wind'];

module.exports = {
  up: queryInterface => {
    return queryInterface.bulkInsert(
      'Elements',
      records.map(name => ({ name, ...baseRecord })),
    );
  },

  down: () => queryInterface =>
    Promise.all([queryInterface.bulkDelete('Elements', null, {})]),
};
```

**Comment by sushantdhiman** [comment]
@enbermudas `down` function is returning another function instead of promise. Here is the correct version

```js
down: queryInterface =>
    Promise.all([queryInterface.bulkDelete('Elements', null, {})]),
```

**Comment by renanmachad** [comment]
The use of `Promise.all ( [ queryInterfaces here] )` , resolves the problem.
