### ISSUE TITLE
Custom storage jsdoc in constructor

### ISSUE THREAD

**Issue by gxcross** [sequelize/umzug#186]
I'm passing a custom storage object in the umzug constructor, which works perfectly. However, the jsdocs for the constructor only allows for strings:

`@param {String} [options.storage='json'] - The storage. Possible values: 'json', 'sequelize', 'mongodb', an argument for require(), including absolute paths.`

Which my IDE (IntelliJ) warns about during type inspection.

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/umzug/commit/328172b7be2e1a25193f6875f6dfcb35a6ff2f3e
