### ISSUE TITLE
Pre and Post event for individual migrations

### ISSUE THREAD

**Issue by daveRanjan** [sequelize/umzug#192]
Hi, I wanted to put a pre-condition before migration starts, if pre-condition failed, I can choose to revert, stop or continue doing migrations.

In my understanding, I need a hook and bind my functions before and after up/down methods are called.

Is there any way of doing this?

**Comment by mmkal** [comment]
@daveRanjan I imagine you found a workaround for this already, but you can use `extend` to achieve this in v3:

```typescript
const { Umzug } = require('./src');

const migratorWithoutHooks = new Umzug({
	...
});

const migrator = migratorWithoutHooks .extend(migrations => {
	return migrations.map(m => ({
		name: m.name,
		up: async () => {
			console.log('some logic before up', m.name);
			await m.up();
			console.log('some logic after up', m.name);
		},
		down: async () => {
			console.log('some logic before down', m.name);
			await m.down();
			console.log('some logic after up', m.name);
		},
	}));
});
```

Feel free to comment here if this doesn't cover your case.

**Comment by papb** [comment]
@mmkal I think he is running several migrations at once and wants to revert everything so far if a certain condition happens before a migration in the middle (with some of them already executed)

**Comment by mmkal** [comment]
I think we should leave that kind of logic to the user - that could either be done manually or with try/catch:


```js
const { Umzug } = require('./src');

class RevertableError extends Error {}

const migratorWithoutHooks = new Umzug({
	...
});

const migrator = migratorWithoutHooks.extend(migrations => {
	return migrations.map(m => ({
		name: m.name,
		up: async () => {
			if (new Date().getDay() === 0) {
			  throw new RevertableError(`Don't run migrations on Sundays!`);
			}
			await m.up();
		},
		down: async () => {
			await m.down();
		},
	}));
});

try {
  await migrator.up();
catch (e) {
  if (e instanceof RevertableError) {
    await migrator.down();
  }
  throw e;
}
