### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by sonicdoe** [sequelize/umzug#197]
Umzug v2.2.0 has been published in November 2018. https://github.com/sequelize/umzug/pull/190 was merged in June 2019 but there hasn’t been a release since. Would it be possible to publish a new version? 🙂

**Comment by papb** [comment]
Hello, sorry about that. @sushantdhiman - is semantic-release supposed to make auto-releases for this package as well? If not, is there a way I can trigger a release, or must it be you?

**Comment by sushantdhiman** [comment]
I can't publish to this package https://www.npmjs.com/package/umzug

![image](https://user-images.githubusercontent.com/9989487/76522162-24927b00-648c-11ea-8f29-eb41f6af60de.png)

**Comment by papb** [comment]
@jukkah @PascalPflaum @sdepold Would one of you be willing to give permissions for me and @sushantdhiman? Thank you :)

**Comment by jukkah** [comment]
Sorry guys. I pretty much ignore everything about this project as I'm not maintaining this any more. But any way, I've now added @sushantdhiman to maintainers of npm package. Please add others and remove me when you have access to it. I didn't remove myself yet that we don't lost access to it in case of failure. And if you need me in the future please contact me via email. That's how I become informed this time too. :smile:

**Comment by sushantdhiman** [comment]
@jukkah Thanks for the quick response :)

@papb I have added you to this package as well, let's discuss release plan for `umzug` and `cli` in docs team

**Comment by sushantdhiman** [comment]
`2.3.0` released on NPM
