### ISSUE TITLE
Reference to Sequelize

### ISSUE THREAD

**Issue by axelhzf** [sequelize/umzug#20]
It's possible pass the reference to Sequelize in the sequelize storage constructor instead of doing this?

[https://github.com/sequelize/umzug/blob/master/lib/storages/sequelize.js#L8](https://github.com/sequelize/umzug/blob/master/lib/storages/sequelize.js#L8)
```js
var Sequelize = require(resolve('sequelize', { basedir: process.cwd() }));
```

I'm working on a framework that depends on this library, but the applications using the framework doesn't depends directly on sequelize.

[https://github.com/axelhzf/barbakoa/blob/master/app/server/migrations.js](https://github.com/axelhzf/barbakoa/blob/master/app/server/migrations.js)

Does this make sense?

**Comment by sdepold** [comment]
Hi :) I didn't yet look into any code but you could also pass a a model rather than the credentials. Would that help?

**Comment by axelhzf** [comment]
No, the problem is the line

```js
var Sequelize = require(resolve('sequelize', { basedir: process.cwd() }));
```
is executed no matter what options are being passed and it throws an Error 

```js
[Error: Cannot find module 'sequelize' from '....']
```

A possible solution would be get the Sequelize reference in the constructor

```js
module.exports = redefine.Class({
  constructor: function (options) {
    this.Sequelize = options.Sequelize || require(resolve('sequelize', { basedir: process.cwd() }));
   
    ...

  }
})
```

**Comment by sdepold** [comment]
Ah I see. Would be fine for me. Want to provide a PR?
