### ISSUE TITLE
Disable log message about wrong file format

### ISSUE THREAD

**Issue by gvko** [sequelize/umzug#200]
I am writing my migrations in TypeScript and when they get transpiled, there are the `.d.ts` and `.js.map` files along with the actual `.js` migration files in the `migrations/` dir. Here's my Umzug config:
```
this.umzug = new Umzug({
      storage: 'sequelize',
      logging: this.logger.info.bind(this.logger),
      storageOptions: {
        sequelize: this.sequelize,
        tableName: app.get('postgres').migrationTable
      },
      migrations: {
        /*
         * The params that get passed to the migrations `up` and `down` functions:
         * (queryInterface, Sequelize)
         */
        params: [this.sequelize.getQueryInterface(), this.sequelize.constructor],
        /*
         * The path to the migrations dir, relative to the root dir
         */
        path: 'dist/migrations',
        /*
         *  The pattern that determines whether or not a file is a migration.
         */
        pattern: /^\d+[\w-_]+\.js$/
      }
    });
```

Because the `pattern` will match only `.js` files to be executed as migrations (as it should be), the `.map` and `.d.ts` files will puke warning logs like:

```
File: 20200314121327-test-migration.d.ts does not match pattern: /^\d+[\w-_]+\.js$/
File: 20200314121327-test-migration.js.map does not match pattern: /^\d+[\w-_]+\.js$/
```

And since I first call `umzug.pending()` and then `umzug.up()`, I will get a warning for each migration *twice*. And this happens for the migrations that are not to be executed as well. It happens on scan of the directory. So, when I have more than a couple of migrations files, you can imagine how flooded the logs become.

Is there a way to suppress this message?

**Comment by sushantdhiman** [comment]
This should be fixed with `2.3.0` release

**Comment by gvko** [comment]
When is that planned to be released, @sushantdhiman ?

**Comment by sushantdhiman** [comment]
Already released
