### ISSUE TITLE
Looking for maintainer(s)

### ISSUE THREAD

**Issue by sushantdhiman** [sequelize/umzug#204]
Hello Everyone,

Umzug has been under unmaintained state for the past year. Recently we got notified about this by https://github.com/sequelize/umzug/issues/197 issue. I have merged some pending pull requests, updated dependencies and released a new version `2.3.0`.

For immediate future me and @papb will be reviewing pull requests. Going forward I would like someone to join us with reviewing pull requests, triaging issues and maintaining this library.

If you are interested you can either comment here or email me `sushantdhiman@outlook.com`.

Also pinging current maintainer (@PascalPflaum), Please share your thoughts and let us know if you will be able to maintain umzug in the near future :)

Thanks!

**Comment by floydspace** [comment]
@sushantdhiman Hi, it's a coincidence that you posted this, yesterday I have implemented a DynamoDB umzug storage here https://github.com/floydspace/dynamodb-migrations-tool/blob/master/src/storages/dynamodb.ts 
You think is it good idea to put it as part of **umzug** repo, or it's better to keep it as separate package?
Thank you

**Comment by papb** [comment]
Hi @floydspace, I think it is better to be kept as a separate package. Thanks though!

**Comment by MatteoGioioso** [comment]
I might be interested!

**Comment by danoseun** [comment]
Hi @sushantdhiman I am interested.

**Comment by sushantdhiman** [comment]
Thank you all who commented or got in touch with me over email for your interest in maintaining this library.

I have invited @mmkal as maintainer for `umzug`. I selected @mmkal as they maintain [slonik-tools ](https://github.com/mmkal/slonik-tools) and contributed to `umzug`

**Comment by sushantdhiman** [comment]
As @mmkal is now officially a member of Sequelize team, I am closing this issue. @papb & @mmkal will takeover maintenance for this module.

**Comment by mmkal** [comment]
Thanks @sushantdhiman!!
