### ISSUE TITLE
(force) execute all migrations?

### ISSUE THREAD

**Issue by AppElent** [sequelize/umzug#212]
Great package!

Is it possible to execute all migrations (both pending and already executed) even if they already executed?
This is because I am using an Umzug instance for my seeds and I want to execute the seeds every time I startup the application.

I know I can grab the executed() and also the pending, and pick all ids, and execute them all by id, but is where any easier way? For example:
umzug.up({from : 0})

**Comment by mmkal** [comment]
Hi @AppElent, did you try using a custom storage? You may be able to extend whichever existing storage you're using, and simply filter out the "seed" migrations in the `executed` function.

**Comment by mmkal** [comment]
Closing - I don't think this use case is common enough to add anything. It's already possible anyway by passing ID explicitly, or writing a modified storage.

**Comment by papb** [comment]
You could also define a `.down` function as no-op for each, and then you start by undoing all migrations and then migrating again. If you already use `.down` functions for something, you could wrap the migrations just for that specific umzug instance, overwriting them:

```js
const umzug = new Umzug({
  migrations: {
    glob: 'migrations/*.js',
    resolve: ({ name, path }) => ({
      name,
      up: require(path).up,
      down: async () => {}
    })
  },
});
```

**Comment by papb** [comment]
@mmkal By the way, is the explicit `down` no-op really necessary in my example, or could it be just omitted? I don't remember :sweat_smile: Is my example code above really correct?

**Comment by mmkal** [comment]
It can be omitted - but in this case I think better to make it an explicit no-op, since it's a little unusual.
