### ISSUE TITLE
Should I make associations in migrations?

### ISSUE THREAD

**Issue by filipedeschamps** [sequelize/umzug#22]
Hi guys! One quick question:

Should I make associations with umzug migrations or Sequelize? Or both?

Best regards!

**Comment by sdepold** [comment]
Both :) you would have to define the tables with migrations and the associations with sequelize

**Comment by filipedeschamps** [comment]
Great! Thanks @sdepold 

Do you know if there's any tool to help me with this task?

**Comment by sdepold** [comment]
Not to my knowledge. We were thinking about a mechanism to generate migrations based one model definitions. But nothing has been implemented so far

**Comment by filipedeschamps** [comment]
You know, I'd wish to be smart one day to be able to contribute to projects/features like this.

So by now, I'm planning to make Sequelize do the first hard lifting, then dump the database and import it in the migration.

*Your Cubi game is awesome!

**Comment by sdepold** [comment]
:D So just for the record: Here is the code that migrates the old meta table to the new one: https://github.com/sequelize/cli/blob/master/lib/tasks/db.js#L226-L284

It's a pretty ugly piece of code but it does it's job :)

**Comment by diosney** [comment]
@filipedeschamps There is always a first time, only you have to try it :) and ask for help if your road is blocked.
