### ISSUE TITLE
down({ to: undefined }) means revert all migrations?

### ISSUE THREAD

**Issue by fwh1990** [sequelize/umzug#230]
`umzug.down({ to: undefined })` has the same behavior with `umzug.down({ to: 0 })`, is the logic correct?

Maybe it should be considered as `umzug.down({})` or `umzug.down()`

**Comment by mmkal** [comment]
I agree, `{ to: undefined }` should be equivalent to `{}`. @papb what do you say we update it to work that way for the v3? This would technically be a breaking change though, so I don't think we can release a fix on v2.

**Comment by fwh1990** [comment]
@mmkal  Fortunately, I'm using v3-beta, thanks for your effort.

**Comment by papb** [comment]
Hello, I agree, `{ to: undefined }` should be equivalent to `{}`
