### ISSUE TITLE
Use umzug to seed the database

### ISSUE THREAD

**Issue by filipedeschamps** [sequelize/umzug#24]
I'm in love with how umzug is simple and easy to use.

And since it's a general task/migration runner, do you think it's a good idea to also use it to seed the database in the right time?

**Comment by sdepold** [comment]
Hi Filipe, 

Thanks :) using umzug for seeding should work nicely, you only need to make sure that you don't run the seeding when you are in an environment where you don't want the seeding :)

**Comment by sdepold** [comment]
You could wrap the seeding migrations in an if block which checks for the environment.

**Comment by filipedeschamps** [comment]
Great!!!

But I will seed it with permanent data, like city names and ids.

Thanks :)

**Comment by sdepold** [comment]
Yeah in that case it should work nicely :)

**Comment by filipedeschamps** [comment]
:+1:

**Comment by mypark** [comment]
are there any examples of running seed data along with the migration?

**Comment by emerak** [comment]
Im trying to seed data but the migrations never says "migrated", only "Migrating", have any idea of why?

**Comment by verjik** [comment]
Could you please elaborate how to seed
Migration and the rest of test code works fine

```
var chai = require('chai');
var should = chai.should();
var chaiHttp = require('chai-http');
chai.use(chaiHttp);

var models = require('../../models');
var server = require('../../app');

var Umzug = require('umzug');
var umzug = new Umzug({
    storage: 'sequelize',

    storageOptions: {
        sequelize: models.sequelize,
    },

    migrations: {
        params: [models.sequelize.getQueryInterface(), models.sequelize.constructor, function () {
            throw new Error('Migration tried to use old style "done" callback. Please upgrade to "umzug" and return a promise instead.');
        }],
        pattern: /\.js$/
    }
});

describe('routes : developer', () => {

    beforeEach((done) => {
        umzug.down({ to: 0 })
            .then(() => umzug.up()
                .then(() => // TODO: how do I seed here ?
                    done()));
    });

    afterEach((done) => {
        umzug.down({ to: 0 })
            .then(() => {
                done();
            })
        });
    });
});
```

**Comment by fakiolinho** [comment]
Any response here? Things are quite blurry regarding seeders.

**Comment by rochapablo** [comment]
+1

**Comment by rochapablo** [comment]
Never mind;

Just changed from
```
path: '../migrations'
```
to
```
path: '../seeders'
```
at
```
new Umzug({...})
```

**Comment by cyrilchapon** [comment]
What about `SequelizeMeta` and `SequelizeData` tables ?

**Comment by LeandroDoldan** [comment]
I would also like to see an example if possible! 👍

**Comment by jagged3dge** [comment]
```js
/* ./migrations.js */
var Sequelize = require("sequelize");
var Umzug = require("umzug");
var models = require("./models");

var migrationsConfig = {
  storage: "sequelize",
  storageOptions: {
    sequelize: Sequelize
  },
  migrations: {
    params: [
      models.sequelize.getQueryInterface(),
      models.sequelize.constructor
    ],
    path: "./migrations",
    pattern: /\.js$/
  }
};

var seedsConfig = {
  storage: "sequelize",
  storageOptions: {
    sequelize: Sequelize,
    modelName: 'SequelizeData' // Or whatever you want to name the seeder storage table
  },
  migrations: {
    params: [
      models.sequelize.getQueryInterface(),
      models.sequelize.constructor
    ],
    path: "./seeds",
    pattern: /\.js$/
  }
};

var migrator = new Umzug(migrationsConfig);
var seeder = new Umzug(seedsConfig);

module.exports = () => migrator.up().then(() => seeder.up());

/* ./index.js */
var migrations = require("./migrations");

// Run migrations & seeds
migrations().then(function() {
  console.log("Migrations completed");
});
```

**Comment by nishant-dani** [comment]
It appears for seeders to work -  migrations and seeders have to be interleaved to match up with the db schema at the time the seeder was written.  Otherwise it could cause issues at runtime if some columns the seeder expects to be there are missing because of migrations.

**Comment by heroneto** [comment]
> Could you please elaborate how to seed
> Migration and the rest of test code works fine
> 
> ```
> var chai = require('chai');
> var should = chai.should();
> var chaiHttp = require('chai-http');
> chai.use(chaiHttp);
> 
> var models = require('../../models');
> var server = require('../../app');
> 
> var Umzug = require('umzug');
> var umzug = new Umzug({
>     storage: 'sequelize',
> 
>     storageOptions: {
>         sequelize: models.sequelize,
>     },
> 
>     migrations: {
>         params: [models.sequelize.getQueryInterface(), models.sequelize.constructor, function () {
>             throw new Error('Migration tried to use old style "done" callback. Please upgrade to "umzug" and return a promise instead.');
>         }],
>         pattern: /\.js$/
>     }
> });
> 
> describe('routes : developer', () => {
> 
>     beforeEach((done) => {
>         umzug.down({ to: 0 })
>             .then(() => umzug.up()
>                 .then(() => // TODO: how do I seed here ?
>                     done()));
>     });
> 
>     afterEach((done) => {
>         umzug.down({ to: 0 })
>             .then(() => {
>                 done();
>             })
>         });
>     });
> });
> ```

Worked for me, thanks.

**Comment by dranitski** [comment]
My 2024 code that works https://stackoverflow.com/a/78306843/10099510
