### ISSUE TITLE
Force uzmug to mark all migrations as applied

### ISSUE THREAD

**Issue by santiagoaguiar** [sequelize/umzug#25]
I want my code to either create the db on startup if not present or otherwise migrate it to the latest version. 

I think have two options: 
1. Create an initial migrator that basically represents the first version of the DB (which usually involves quite a lot of tables...), and then apply all the migrations.
2. Do a `sync()`.

If I do 2, which I would prefer in principle to avoid having to duplicate the DB schema already described on the sequelize model, then, after the sync, no migrations will have been recorded, so they will try to be reapplied, which causes issues since he model has been synced before.

Is there a way to tell umzug to record all the migrations as done even if they have not been actually executed? Or should I do that on the `up()` method itself? Example, add some argument somewhere and do: 

```
up() {
  if (!creating_from_scratch) {migrate...}
}
```

Suggestions welcomed ;).

**Comment by sdepold** [comment]
Hi @santiagoaguiar,

in general `sync` is more meant to be a development tool rather than something you want to run in production. Ideally everything that is needed inside your db is shipped as a migration. There have been plans to export a model schema as a migration, but nothing has been done so far. (you might want to do that :)) I'd rather not add the if clause to your migrations tbh. imho you should ship a first version of your db as a migration and build everything on top of that.

**Comment by santiagoaguiar** [comment]
Ok, thanks! I kind of assumed that might be the answer!! 

It does pain me a little, not only because of the duplication, but because migrations are written by referring to tables. columns and indexes whose names are usually defined by sequelize. So I guess I either go and be explicit about those on the model definition, or use the names I expect sequelize to generate, which will be a kind of 'magic names' for other readers of the code :).

Not comfy enough yet with sequelize to tackle this by a PR. I guess I'll go with be explicit route! Thanks!

**Comment by sdepold** [comment]
yeah explicitly defining table and column names might be a good choice in that case :)

**Comment by sdepold** [comment]
How much would you benefit of a tool that would generate the migration for a model?

**Comment by rpaterson** [comment]
+1 to the OP's original request (mark all migrations as "done").  I wanted this too and ended up writing a custom solution for it that duplicates some of Umzug's logic.  It would be much nicer if this was built in.

**Comment by filipedeschamps** [comment]
-1 to mark all migrations as done, looks like a workaround to what you
really want to accomplish

+1 to create migrations based on models, because you can't mess up in this
stage :)

**Comment by santiagoaguiar** [comment]
I would definitely benefit from something that created the migrations.

I think marking as done might be useful, in any case. When creating a db from scratch, running all the migrations up to that point might be a bit of an overkill, I would prefer to create it as it stands now ,and applies migrations from that point forward, but I'll agree that migrating from scratch is a good way to make sure your migrations are robust enough ;).

One argument against running migrations from scratch: we devel on sqlite on some cases, though our target DB is mysql. SQLite does not like some kind of migrations (e.g. drop a column). So I would prefer being able to drop the table and let my code recreate it from scratch, than let it be recreated applying migrations, since those will fail. A weak argument anyway ;).

Being able to write migrations by talking about the model instead of the DB would definitely be a plus too (ie. no 'add column to table', but 'add property to model').

**Comment by rpaterson** [comment]
Lots of tools have an option that just makes it look liked the action happened without actually performing the action - this would be analogous.

**Comment by filipedeschamps** [comment]
I think they're considering to add a kind of auto mode to Sequelize sync api, like `.sync({auto: true})` to just change what's necessary from the current database state.

But anyway, can't you just skip the migration in your startup workflow and `.sync({force: true})` in your app?

**Comment by mdarveau** [comment]
This is what I did (coffeescript):
```
  markMigrationsAsRan = (umzug)->
    console.log "Marking migrations as ran..."
    umzug.pending()
    .each (migration)->
      console.log "Marking migration '#{migration.file}' as ran"
      umzug.storage.logMigration(migration.file)
```

**Comment by mmkal** [comment]
Closing, this is a very old issue. As @mdarveau suggested this can be done by iterating through pending migrations. In v3 you'll be able to use the `.extend` and wrap each migration with a no-op `up` function. Anyone looking for something like this, I'd suggest opening a new issue because the API has changed since 2015(!)
