### ISSUE TITLE
Umzug Questions

### ISSUE THREAD

**Issue by juliocanares** [sequelize/umzug#26]
Hi guys I'm using umzug in this days :D and I have a questions

1- Is need describe the properties of the table in the model and migration ?. I seem redundant make in two places.

2 - When in my migration delete a column email , and my user model too have the property email , when the migration is executed this delete the email column , but my model still follow with the email property , I need delete the email property of the model manually  ? 

3- Is possible execute the umzug migrations by cli ?, because now I need run the server for up migrations and execute another time for down migrations.

thanks :D

**Comment by filipedeschamps** [comment]
@juliocanares I'm no Umzug pro user, but I will try to help:

1) Currently yes, there's no tool to generate migration files based on model definitions. But they are considering to do it.

2) Yes, your model should be in the exact same state of the last migration.

3) Yes there is, it's called Squelize CLI and it uses Umzug under the hood: https://github.com/sequelize/cli

**Comment by sdepold** [comment]
Hi @juliocanares,

@filipedeschamps is totally right. You currently have to have the data in both places, you will have to manually delete the properties from the model if you drop them via migration, the CLI uses umzug internally.
