### ISSUE TITLE
SequelizeMeta in different schema

### ISSUE THREAD

**Issue by DenisFerrero** [sequelize/umzug#261]
Hi guys, is there any way to choose in which schema SequelizeMeta table have to be created? I create different schema through my interface and each schema has the same tables but the SequelizeMeta has still be created in the public ones even if to the storageOptions of Umzug I use the sequelize instance of that schema

**Comment by papb** [comment]
[It should be with `v3`](https://github.com/sequelize/umzug/blob/6d6cc4260206df51ff27a7fd4c2a1fca8e0b20c8/src/storage/sequelize.ts#L39).

```js
const umzug = new Umzug({
  migrations: { glob: 'migrations/*.js' },
  context: sequelize.getQueryInterface(),
  storage: new SequelizeStorage({ sequelize, schema: 'foobar' }),
  logger: console,
});
```

Please try it and let me know. I will reopen the issue if it doesn't work. Thanks!
