### ISSUE TITLE
Umzug Up Method Proper Usage

### ISSUE THREAD

**Issue by Hirobreak** [sequelize/umzug#269]
Hello, more than an issue, I'm having a bit of a hard time understanding how the method `up` works when I pass an array of migration filenames.

Let's say I run 
```
try {
  await migrator.up(['m1.js', 'm2.js', 'm3.js']); //migrator is an instance of umzug
} catch (error) {
  console.error(error);
}
```

1.- Migrations will run sequentially? 
2.- If `m2.js` fails, will `m3.js` run?
3.- Is there a case where the `catch` block will be triggered?

**Comment by mmkal** [comment]
1. Yes, migrations run sequentially
2. If m2 fails, m3 won't run
3. The catch block will be entered if any of the migrations throw an error
