### ISSUE TITLE
Understanding Sync

### ISSUE THREAD

**Issue by zeeshanjan82** [sequelize/umzug#30]
I am having a hard time to understand how can I sync my Sequelize models with the mysql database. After doing lot of googling I came to Umzug and really was looking for an example which could show me how can I sync my models written in Sequelize with mysql or mariadb using Umzug. Also I did not really find the gulp module which could do that.

Can you guys point me to some place where I can find an example of using Umzug with Sequelize.

**Comment by sdepold** [comment]
Related to https://github.com/sequelize/sequelize/issues/2670

You basically have 2 options: There is the function `sequelize.sync` which will create the schema defined in your sequelize models and then there are migrations which are not really related to your actual code at all. Migrations are files that describe how to achieve a certain task how. In terms of database stuff (please note that umzug can potentially be used for non-db tasks) that means you are describing how to upgrade or downgrade your db from a specific point in time.

So if you have a user table and want to add a column username you would create a migration which adds the column respectively:

```
module.exports = {
  up: function (queryInterface) {
    return queryInterface.addColumn('users', 'username', 'STRING');
  } 
}
```

Now you can run the sequelize cli or a piece of code that calls umzug to execute that file.
There is currently no way to generate a migration from an existing sequelize model.

**Comment by zeeshanjan82** [comment]
Thanks @sdepold  but I feel its really a lot of work for a developer to maintain the migrations scripts, I agree that it has huge benifits and in case of production env. It makes sense to have migration scripts created and maintained but during the development process using only sync feature of sequelize does not seem enough. I am really looking for an approach using sync where it itself detects the changes in models and performs a sync. Now its doing it everytime and if I use the force:true option.

**Comment by sdepold** [comment]
I can't agree more. But there aren't any plans yet to implement that.

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/issues/537

**Comment by manast** [comment]
adding new columns should not require any migration script, this is mostly trivial, and is really amazing this is not implemented yet. A different case is if you remove columns, but works case, I want .sync to tell me that my model is not "in sync" with the model in the SQL database. This kind of "failing silently" is really a no-go that will create bugs in the future almost guaranteed.

**Comment by felixfbecker** [comment]
@ma say PRs welcome

**Comment by jukkah** [comment]
@manast Yeah that's a problem of Sequelize (another repo) not umzug (this repo).

I close this issue as there is nothing umzug related at all. (Why? Umzug is only a migration manager and it is actually Sequelize who migrates the database when using Sequelize and Umzug together.)
