### ISSUE TITLE
Problem not finding the migration file

### ISSUE THREAD

**Issue by yayolius** [sequelize/umzug#32]
Hi, first day working with the migration and i am stuck.
I have a migration working on console (db:migrate), but when i remove it and try to use umzug it gives me this error:
Unhandled rejection Error: Unable to find migration: [object Object]

The migration object is:

{ path: '(nothing to show)/backend/server/migrations/20150724131728-create-sections.js',
  file: '20150724131728-create-sections.js',
  options:
   { storage: 'sequelize',
     storageOptions:
      { modelName: 'SequelizeMeta',
        columnName: 'name',
        sequelize: [Object],
        model: [Object] },
     logging: [Function],
     upName: 'up',
     downName: 'down',
     migrations:
      { params: [],
        path: 'server/migrations',
        pattern: /^\d+[\w-]+.js$/,
        wrap: [Function] } } }

The only difference i think is that the script is running with "server/app.js" and the migrations are in folder server/migrations, i properly configured umzung for that with:

var umzug = new Umzug({
                        storage: 'sequelize',
                        logging: console.log,
                        storageOptions: {
                            sequelize: app.get("sequelize")
                        },
                        migrations: {
                            path: 'server/migrations' 
                        }
                    });

I also tried to just move the migration folder outside the server folder and changing the configuration but that did not worked either.

Please help, i really want to use this but i cannot, if i cannot make it work with just one migration file.

**Comment by filipedeschamps** [comment]
Have you tried to use other strategies in the path, por example './server/migrations' or resolve the full path?

I'm resolving the full path and it's working 100%:

**Migration logic**
https://github.com/filipedeschamps/insiderNews/blob/master/core/server/database/migrations.js#L18

**Settings**
https://github.com/filipedeschamps/insiderNews/blob/master/core/configurations/base.js#L15

**Comment by yayolius** [comment]
thanks i will try this!

2015-07-25 12:05 GMT-03:00 Filipe Deschamps <notifications@github.com>:

**Comment by filipedeschamps** [comment]
Great! Let us know how it went to close the issue :+1:

**Comment by yayolius** [comment]
Ok, i think i found a bug:
Here: https://github.com/sequelize/umzug/blob/master/lib/migration.js#L41

```javascript
  testFileName: function (needle) {
    return this.file.indexOf(needle) === 0; //HERE
  },
```

needle is an object that has the properties path,files,options and not an string so you can do a indexOf comparassion, instead it just fails because it cannot find anything, if i change that line for

```javascript
  testFileName: function (needle) {
    return this.file.indexOf(needle.file) === 0;
  },
```

It works perfectly.
Can you test that? at least changing it in my local node_modules did the work, please check!

**Comment by yayolius** [comment]
Well i had no response, i will fork the repository with my solution in the meantime

**Comment by sdepold** [comment]
Pull requests are more than welcome :)

**Comment by cglantschnig** [comment]
do you have an idea what I am doing wrong there?

Here the file where I create the Umzug Object. The file is located in `src/shared/utils/migrate.js`. My migration files are located in `src/shared/migrations` and are called like `001-name.js`. If I call `umzug.pending()` always returns an empty array. The sequelize connection works fine. The `SequelizeMeta` Table is getting created, it just cant find the migration files.

```javascript
import path from 'path';
import Umzug from 'umzug';
import config from '../config';
import { sequelize, Sequelize } from '../models/';

var umzug = new Umzug({
  // The logging function.
  // A function that gets executed everytime migrations start and have ended.
  logging: function(info) {
    console.log(info);
  },

  // The storage.
  // Possible values: 'json', 'sequelize', an object
  storage: 'sequelize',

  // The options for the storage.
  // Check the available storages for further details.
  storageOptions: {
    sequelize: sequelize
  },

  migrations: {
    // The params that gets passed to the migrations.
    // Might be an array or a synchronous function which returns an array.
    params: [sequelize.getQueryInterface(), Sequelize],

    // The path to the migrations directory.
    path: path.join(__dirname, '../migrations'),

    // The pattern that determines whether or not a file is a migration.
    pattern: /^\d+[\w-]+\.js$/
  }
});

/**
 * executes all migrations
 */
export function up() {
  return umzug
    .executed()
    .then(function(executedMigrations) {
      console.log(executedMigrations);
      return umzug.pending();
    })
    .then(function(pendingMigrations) {
      if (pendingMigrations > 0) {
        return umzug.up();
      }
      console.log('All migrations set!');
    });
}
```

**Comment by zeorin** [comment]
Hi, I have the same error. My code is as follows:

```javascript
gulp.task('migrate', function (cb) {
    const sequelize = new Sequelize(dbConfig.database, dbConfig.username, dbConfig.password, dbConfig);
    const umzug = new Umzug({
        storage: 'sequelize',
        storageOptions: {
            sequelize: sequelize
        },
        migrations: {
            params: [sequelize.getQueryInterface(), sequelize.constructor],
            path: './migrations',
            pattern: /^\d+[\w-]+\.js$/
        }
    });

    umzug.pending().then(function (migrations) {
        umzug.execute({
            migrations: migrations,
            method: 'up'
        }).then(function (migrations) {
            cb();
        });
    });
});
```

If I `console.log` the `migrations` that `umzug.pending()` provides for its `then` function, I see that it's not actually an array with the names of the migrations, but an array of migration *objects*. The docs say that it's supposed to be an array of migration names.

Rather than editing the sequelize code and having to keep that up to date, I inserted a simple map function that solved the issue for me:

```javascript
    umzug.pending().then(function (migrations) {
        migrations = migrations.map(function (migration) {
            return migration.file.replace(/\.js$/, '');
        });
        umzug.execute({
            migrations: migrations,
            method: 'up'
        }).then(function (migrations) {
            cb();
        });
    });
```
Either there's a bug in the `pending` function, or the docs are out of date.

**Comment by joehenry087** [comment]
@zeorin, nice. Had the same problem. Thanks for the fix.

**Comment by jukkah** [comment]
I think our docs are out of date but the API is inconsistent too.

```js
// execute pending should be written like this
umzug.pending().then(migrations => {
  umzug.execute({ migrations: migrations, ... }).then(...);
);
```

**Comment by jukkah** [comment]
@yayolius Your bug still exists. I'll fix it in version 2.0.

**Comment by elemanhillary** [comment]
@yayolius navigate to your database client a table called `SequelizeMeta` and run again

**Comment by marcopetry** [comment]
I created 20150724131728-create-sections.js' within backend/server/migrations/ with anything on down method and run. After deleted the archived and never more has that issue.

In my case, i has created a model and update name after, that generated error.

**Comment by mmkal** [comment]
Closing - the `indexOf == 0` check is gone in v3. If anyone sees a similar problem, please raise a new issue.
