### ISSUE TITLE
Incorrect migration being executed (v2.3.0)

### ISSUE THREAD

**Issue by kylelynchkurzawa** [sequelize/umzug#324]
I have added v2.3.0 of umzug to a project to handle database migrations. Previously my project's migrations using umzug have been ran and executed successfully until I added a new pair of migration files.

Files that have been added:
```
/migrations/v3-tables.js
/migrations/v3-tables-constraints.js
```
I have defined the order that the migrations have to be ran in by using a separate JSON file to store / manage that called "migrations-list.json"
```json
{
  "up": [
    ...
    "v3-tables",
    "v3-tables-constraints"
  ],
  "down": [
    ...
  ]
}
```
And I execute them using the following async method to ensure they get executed sequentially.
```javascript
const migrationsList = require('./migrations-list.json');

const invokeUpMigrations = async function(){
    //query umzug for any migrations that are pending (aka. that haven't ran)
    const pendingMigrations = await umzug.pending();
    //filter out the migration names array based on if there is a pending migration with that file name
    const filteredMigrationIds = migrationsList.up.filter((migrationId) => {
        return pendingMigrations.some((pendingMigration) => {
            return (pendingMigration.file === (migrationId+'.js'));
        });
    });
    //execute each migration name that is pending in the order from the "migrationsList"
    for(const migrationId of filteredMigrationIds){
        await umzug.up(migrationId);
    }
};
```

I found that within the function _findMigration() in /lib/index.js when it is testing the file name of the migration using migration.testFileName(needle) it gets returned the incorrect boolean value when comparing the **needle** parameter of "v3-tables" against the value of **this.file** with the value of "v3-tables-constraints" since it is using **.indexOf()**
_findMigration() snippet:
```javascript
_findMigration(needle) {
    return this._findMigrations().then(migrations => migrations.filter(migration => migration.testFileName(needle))[0]).then(migration => {
      if (migration) {
        return migration;
      } else {
        return _bluebird.default.reject(new Error('Unable to find migration: ' + needle));
      }
    });
  }
```
_testFileName() snippet from "/lib/migration.js"
```javascript
  testFileName(needle) {
    return this.file.indexOf(needle) === 0;
  }
```

Is .indexOf() the intended way of comparing the migration names and can this be addressed in a future release of v2 (or in the v3 beta if it's present there)?
Is there a known work around this edge case without having to change the names of my migration files?

**Comment by mmkal** [comment]
This is fixed in https://github.com/sequelize/umzug/pull/325 so if that lands soon the issue will be addressed in v3. I'll add an explicit test case to that PR. For now, there's no workaround and introducing one would be a breaking change so likely there will not be a fix for v2. The simplest solution would be to rename your migrations, but failing that you may need to `require` the Migration class and patch `Migration.prototype.testFileName`.

**Comment by kylelynchkurzawa** [comment]
@mmkal Thank you, I did end up renaming my migration files to avoid this issue. Thank you for including it in that PR.
