### ISSUE TITLE
How should the logger process its arguments

### ISSUE THREAD

**Issue by stefaanMLB** [sequelize/umzug#326]
I need to log the umzug messages to Winston.
Setting logger=console.log works fine.  Assigning a Winston logger doesn't work.
For now I'm using `logging: (...args: any[]) =>log.info(args[0]);` which works but doesn't seem right.
Could you document exactly how the logging function should process the `...args` arguments ?

**Comment by mmkal** [comment]
Right now, only plain strings are logged, so your solution will work. But it may make sense to change the log function signature to `(message: string) => void` to make this clearer.

In https://github.com/sequelize/umzug/pull/325 `logging` is replaced with a `logger` (with info, warn and debug methods). It should be possible to test that it accepts a few different kinds of loggers, including winston.
