### ISSUE TITLE
feat: Add support for multiple models and migrations folders

### ISSUE THREAD

**Issue by diosney** [sequelize/umzug#33]
This will accomodate an HMVC structure which the models and migrations are segmented across modules.

**Comment by diosney** [comment]
I've not test this yet, but I think that creating a new **umzug** instance per migration folder could be a way to solve this, despite of being overkill.

**Comment by sdepold** [comment]
Hm not sure if this is an issue with umzug as that can already be configured with a different migraiton folder path. Could you open another issue in the cli project https://github.com/sequelize/cli and explain in a more detailed way what functionality you need and what use-case you want to solve?

**Comment by jukkah** [comment]
This is an interesting issue. If I got it, you have some migrations (and models) defined in your app + in a couple of plugin modules and you are trying to migrate them all at once. E.g. `./migrations`, `./node_modules/plugin1/migrations`, and `./node_modules/plugin2/migrations`.

I think this can be solved (for part of umzug) by allowing `options.migrations.path` to be an array.

**Comment by diosney** [comment]
@jukkah Exactly like that! Something like the Django migrations already do with its "applications" (like plugins) and its nested migrations per application.

I agree that umzug allowing an array of path could solve this issue, but only if it accepts to a path **glob**, we can do something like:

```js
paths: [
     '**/migrations/**'
]
```

**Comment by diosney** [comment]
@sdepold, @jukkah already explained exactly what I was asking for, which is not solved by specifying a **different migration folder path**, but specifying  a **collection of migration paths, globs including**.

**Comment by jukkah** [comment]
@diosney Are you planning to implement this by yourself?

**Comment by diosney** [comment]
@jukkah Right now I can't do it since I'm short of time, but if the time comes in the couple of months I will ask you for  help so I can do it, if this is okey for you.

**Comment by diosney** [comment]
@jukkah I need this now and have spare time to work on it, can you point me in the right direction to not work on something wrong?

How this relates to https://github.com/sequelize/cli since it is there where I need this feature?

**Comment by jukkah** [comment]
@diosney Sorry for delay. I'm designing v2.0 and globs are one of its main enhancements. I don't know yet how this should be enabled in sequelize-cli, but I will work on it in the future.

**Comment by diosney** [comment]
@jukkah nice!

**Comment by framled** [comment]
what is the status of this?

**Comment by jpaulo1987** [comment]
I also would like to know the status of this, since i am adopting a decentralized structure in a project i am doing.
