### ISSUE TITLE
Umzug with mongodb fails to compile with tsc

### ISSUE THREAD

**Issue by olehdevua** [sequelize/umzug#348]
I use `umzug` to run `mongodb` migrations. I also use typescript in my project.
When I try to compile my project I have next error:

> node_modules/umzug/lib/storage/sequelize.d.ts:3:65 - error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
> 
> 3 import { Sequelize as SequelizeType, Model as ModelClass } from 'sequelize';

Is it possible to use `umzug` without `sequelize` with typescript. Maybe I'm missing something.

**Comment by mmkal** [comment]
@olehdevua thanks for the report. This is a bug, should be possible to fix this week. Just to check - are you using v3 beta?

**Comment by papb** [comment]
> Is it possible to use `umzug` without `sequelize` with typescript. Maybe I'm missing something.

Should definitely be possible.

However, I was not able to reproduce, can you provide a minimal example? @mmkal did you reproduce it?

**Comment by mmkal** [comment]
Yes I was able to reproduce. No problems show up in vscode but when compiling with `tsc` it errors.
