### ISSUE TITLE
[v3 beta6] Conflicting documentation on context injection

### ISSUE THREAD

**Issue by MichielDeMey** [sequelize/umzug#352]
According to the release log for beta6, `context` should be injected on the `up` and `down` functions respectively.

```js
migrations: {
    resolve({ path }) {
      const { up, down } = require(path);

      return {
          up: ({ context }) => up(context),        // <-- context here?
 	  down: ({ context }) => down(context)     // <-- context here?
      }
  }
},
context: sequelize.getQueryInterface(),
```

However, when looking at the PR (https://github.com/sequelize/umzug/pull/325) I can see that the context should come from the `resolve` function, which I found to work for the beta6 release:

```js
migrations: {
    resolve({ path, context }) {      // <-- Context is actually here
      const { up, down } = require(path);

      return {
          up: () => up(context),
 	  down: () => down(context)
      }
  }
},
```

Just wanted to point out some confusion. 🙂

**Comment by mmkal** [comment]
@MichielDeMey thanks for the report! I can get to this sometime this week, but a PR would also be v welcome 🙃

**Comment by MichielDeMey** [comment]
I'd love to, but I cannot create a PR for release logs. 😅
https://github.com/sequelize/umzug/releases/tag/v3.0.0-beta.6

**Comment by mmkal** [comment]
Ah! Thought it was the readme. Will edit.

**Comment by papb** [comment]
Hi @MichielDeMey, I thought both approaches should work. Are you sure the way I wrote in the release notes doesn't work?

@mmkal if it doesn't work that's a bug, right? It should work I think

**Comment by mmkal** [comment]
@papb no, the `up` and `down` functions returns by `resolve` don't receive any parameters. The type system enforces this normally, it just isn't running on our release markdown. I've clarified this here, since the `spy.bind(null, ...)` voodoo made this hard to intuit: https://github.com/sequelize/umzug/pull/355
