### ISSUE TITLE
[v3 beta6] Migration names missing file extensions

### ISSUE THREAD

**Issue by MichielDeMey** [sequelize/umzug#353]
Before the new globbing feature, Umzug stored the migration as the full filename (e.g. `123456-foo.js`) but with the new globbing feature it looks like it's storing the actual name of the migration without the file extension.

See line 371, which strips the file extension for the name
https://github.com/sequelize/umzug/blob/006036ae77ed6fbff9d06e89ad4690ff51a9c2a7/src/umzug.ts#L371-L376

And is then used as the migration name in the "name" column of the migration table
https://github.com/sequelize/umzug/blob/006036ae77ed6fbff9d06e89ad4690ff51a9c2a7/src/umzug.ts#L272

This introduces a major breaking change in existing Umzug installations as the name is different and thus tries to apply every migration again and ends up adding duplicate migrations to the migration table.

| name |
|------|
| 123456-foo |
| 123456-foo.js |

**Comment by mmkal** [comment]
Good catch - I agree, this is an unnecessarily disruptive breaking change; will revert to the existing naming convention before the stable release. In the meantime, if you'd like to keep testing the beta, you should be able to work around by manually adding the file extension in a `resolve` function.

**Comment by papb** [comment]
Thanks for the report and for using the beta version :rocket:

**Comment by djejaquino** [comment]
This should've been documented in [releases](https://github.com/sequelize/umzug/releases) as a breaking change.

**Comment by djejaquino** [comment]
This should have been documented in [beta7 ](https://github.com/sequelize/umzug/releases/tag/v3.0.0-beta.7) as a breaking change

**Comment by mmkal** [comment]
Agreed - sorry for that and I hope it wasn't too disruptive. Have updated that release to mark that change as breaking.

**Comment by djejaquino** [comment]
@mmkal for now, I am fixing my dependency to `"umzug": "3.0.0-beta.6"` in `package.json`
but do you have a clear migration path so we can upgrade umzug? Our `SequelizeMeta` table holds records without file extension in `name` column

**Comment by mmkal** [comment]
@djejaquino one thing I've experimented with locally is a `baseline` command like in [flyway](https://flywaydb.org/documentation/usage/commandline/baseline).

Usage would be something like `node migrate baseline --to some-migration-name.js`. That would just mark everything up to and including `some-migration-name.js` as executed, with the rest pending. If you're in a good state on beta.6 and the db has migrations up to `some-migration-name` stored, baseline would effectively just add the `.js` extension to each one.

Would something like that help?

**Comment by djejaquino** [comment]
@mmkal we don't really have clearance to run arbitrary commands on our hosted environments like that. But we do for arbitrary maintenance SQL scripts. When time comes to upgrade `umzug` dependency, I'll run something like this:
```sql
UPDATE "SequelizeMeta" set name = CONCAT(name, '.ts')
```

**Comment by mmkal** [comment]
I see - curious how you run regular migrations in that case?

Note that there'd also be an equivalent API - `await migrator.baseline({ to: 'some-migration-name.ts' })`

**Comment by djejaquino** [comment]
> I see - curious how you run regular migrations in that case?

Migrations are run through a npm script `"db:migrate": "ts-node migrate.ts"`, which is [run by Heroku release phase](https://devcenter.heroku.com/articles/release-phase#specifying-release-phase-tasks).
This is how our Procfile looks like:
```
web: yarn run start:prod
release: yarn run db:migrate
```

> Note that there'd also be an equivalent API - `await migrator.baseline({ to: 'some-migration-name.ts' })`
> 
> Edit: oh do you mean passing in the specific `some-migration-name.ts` value would require hard-coding it somewhere

Precisely.
