### ISSUE TITLE
Squashed migrations

### ISSUE THREAD

**Issue by jukkah** [sequelize/umzug#39]
Is there any way to combine migrations to squashed migrations and run them instead of the original migrations? Currently no, I guess.

As you know, if there is a zillion of migrations, running them all from the beginning to the end may take a while. In addition, if you have software@1.2 and you upgrade it to software@2.0, performance of the database migration matters.

For example, [Django](https://docs.djangoproject.com/en/1.8/topics/migrations/#squashing-migrations) have some kind of implementation for squashed migrations. I'm not sure if Django replaces migrations with squashed ones, but I think it's better to save them just in case. So there should be all the migrations **plus** some squashed migrations.

![migrations](https://cloud.githubusercontent.com/assets/1504091/11429449/88bc5a8c-9480-11e5-929f-ba4888fcc3a1.png)

In the picture above, black dots are migrations created between releases. Bellow the migrations are squashed migrations. In this example, there are squashes for each minor and major release and one from the beginning to the latest release.

I think, in umzug, we need only
- a list of migrations combined into each squashed migration,
- a way to figure out what squash to use if any, and
- a way to make difference between migrations and squashes.

I can implement this feature but it needs some discussion first.

**Comment by sdepold** [comment]
How would this mechanism be applied? Is that a runtime feature that is executed when running `up` or `down` or is it an extra command that squashes the existing migrations?

**Comment by jukkah** [comment]
This would be a runtime feature. Because we don't care about implementations of `up` and `down` functions, we don't need to analyze them to figure out how to squash them. If some other libraries can create migrations they should also squash them.

My vision of squash file is to follow syntax of migration file:
```javascript
'use strict';

var Bluebird = require('bluebird');

module.exports = {
  // List of migrations squashed in this squash file.
  migrations: ['some-id', 'some-other-id'],

  up: function () {
    return new Bluebird(function (resolve, reject) {
      // Describe how to achieve the task.
      // Call resolve/reject at some point.
    });
  },

  down: function () {
    return new Bluebird(function (resolve, reject) {
      // Describe how to revert the task.
      // Call resolve/reject at some point.
    });
  }
};
```

When running `up` and `down` we (un)log each of listed migrations.

These files should be stored in `squashes` sub-directory or something like that. Another way is to use file names not starting with number. This allows us to require them all at the beginning and then figure out the "best way".

**Comment by sdepold** [comment]
tbh I don't see a major benefit unless we are also implementing this:

```
then running an optimizer over them to try and reduce the length of the list - for example, it knows that CreateModel and DeleteModel cancel each other out, and it knows that AddField can be rolled into CreateModel.
```

are you planning to do this too? or are we just talking about the amount of migrations being executed?

**Comment by jukkah** [comment]
Yeah, of course, you got the point. :+1:

**Comment by sdepold** [comment]
Alright. The interesting part is that umzug is a framework agnostic tool which you may or may not use with Sequelize. While I don't mind have a good portion of sequelize specific helpers in umzug please keep in mind that umzug is can also be used without sequelize and with any available sequelize versions out there.

**Comment by papb** [comment]
> 
> 
> tbh I don't see a major benefit unless we are also implementing this:
> 
> ```
> then running an optimizer over them to try and reduce the length of the list - for example, it knows that CreateModel and DeleteModel cancel each other out, and it knows that AddField can be rolled into CreateModel.
> ```
> 
> are you planning to do this too? or are we just talking about the amount of migrations being executed?

I agree, and I think doing this is extremely complex... I am surprised Django can do it. This looks borderline Halting Problem to me :sweat_smile: 

@jukkah Do you remember how you were thinking of doing this?

@mmkal Do you think this is doable? I wouldn't mind closing as wontfix
