### ISSUE TITLE
Run migrations in a multy tenancy environment

### ISSUE THREAD

**Issue by mario-lemes** [sequelize/umzug#401]
Hey guys,

I got stuck trying to adapt an automatic migration process at runtime in a multi-tenancy environment. I have been digging through the issues but it seems there is nothing similar to what I want to achieve. Any help would be greatly appreciated.

### Scenario

**sequelize**:  6.3.5
**umzug**: 3.0.0-beta.9
**dialect**: postgresql
**store**: SequelizeStorage 

For each tenant created at runtime, I run a migration process, however, it does not allow to run multiple times the same migration because of expected reasons (on the first migration it creates a new record with the migration name on the table "SequelizeMeta" in the "public" schema). 

Based on that, I tried two different approaches:

### 1st approach

By passing `{migrations: [...], rerun: 'ALLOW'}`  to `umzug.up()` I ensure the migration process runs anytime I call the function and the I just to go through all the tenants on the migration file and running all the actions:
```
// roles-migrations.js
async function up({ context: queryInterface }) {
  const schemas = await queryInterface.showAllSchemas();
  for (const schema of schemas) {
    await queryInterface.bulkInsert({ tableName: 'roles', schema }, [
      {
        id: 'admins',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 'users',
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);
  }
}

async function down({ context: queryInterface }) {
  const schemas = await queryInterface.showAllSchemas();
  for (const schema of schemas) {
      await queryInterface.bulkDelete({ tableName: 'roles', schema }, null, {});
  }
}

module.exports = { up, down };
```
The problem with this approach is that the second time I call to `umzug.up()` will try to run the migration again in the first tenant which it's already done so it will throw an expected 'duplicated key error'.

### 2nd approach

In this approach, I went a bit further playing around with the sequelize object but with no success. Basically, I tried to instantiate a new Umzug instance fo each time I wanted to run the migration process but also didn't work. This still creates the "SequelizeMeta" table in "public" 

```
async function runMigration(schema) {
      const umzug = new Umzug({
        migrations: { glob: 'migrations/*.js' },
        context: sequelize.getQueryInterface(),
        storage: new SequelizeStorage({
          sequelize,
          schema
        }),
      });

      await umzug.up();
}
```

Any help is really appreciated.

Thanks.

**Comment by mmkal** [comment]
Your 2nd approach above looks sensible to me. What value does `schema` have? Umzug _should_ be respecting that, and not putting the model in `public` every time.

Side note - make sure you `return umzug.up()` so it's not a floating promise.

**Comment by mario-lemes** [comment]
Hi @mmkal,

Thanks for your response!

In the second approach, `schema` is a string value with the schema name (tenant) but you got to the point because somehow I was not setting properly that value. Thanks for that!

Now that umzug is working as expected I got into a new situation. So, basically, since I'm calling `umzug.up()` per tenant migration, I don't need to go through all the tenant in the `migration.js` file because will cause duplicated index so let's get rid of that loop:
```
// roles-migrations.js
async function up({ context: queryInterface }) {
    await queryInterface.bulkInsert('roles', [
      {
        id: 'admins',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 'users',
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);
}

async function down({ context: queryInterface }) {
    await queryInterface.bulkDelete('roles', null, {});
}

module.exports = { up, down };
```
But what happened is that it throws the next error `Error: 'SequelizeDatabaseError: «roles» relation does not exist`.  And actually make sense! The `queryInterface` belongs to the `sequelize` instance which does not have any schema established on its initialization because all this happens in runtime, so by default is looking into the `public` schema (based on the Sequelize documentation). So, now I need to look for a way to pass the `schema` value to `up()` and `down()` function from the migration file in order to address properly the queries. From umzug it seems only sends `queryInterface` and I haven't figured how to pass anything else out so I got with this dirty workaround:

```
async migrate(schemaName) {
      // Hardcoding the schema name into the sequelize connection options payload in runtime.
      connection.options.schema = schemaName;

      const umzug = new Umzug({
        migrations: { glob: 'migrations/*.js' },
        context: this.connection.getQueryInterface(),
        storage: new SequelizeStorage({
          sequelize: connection,
          modelName: 'migrations_meta',
          schema: schemaName,
        }),
        logger: databaseLogger.logger,
      });

      await umzug.up();     
}
```

I'm not aware at the moment of the possible side effects of this but since I haven't found any mechanism provided by sequelize to change the schema other than in the query functions itself I came up with that solution.

What do you think?

Thanks,
Mario.

**Comment by mmkal** [comment]
Hi - will be able to take a closer look later this week, but this should absolutely be possible. You can pass anything you like to context, passing the queryInterface object is just an optional convention:

```js
async migrate(schemaName) {
      // Hardcoding the schema name into the sequelize connection options payload in runtime.
      connection.options.schema = schemaName;

      const umzug = new Umzug({
        migrations: { glob: 'migrations/*.js' },
        context: {
          queryInterface: this.connection.getQueryInterface(),
          schemaName,
        },
        storage: new SequelizeStorage({
          sequelize: connection,
          modelName: 'migrations_meta',
          schema: schemaName,
        }),
        logger: databaseLogger.logger,
      });

      await umzug.up();     
      connection.options.schema = undefined;
}
```

Then in your migration(s), change how you use context slightly:

```js
// roles-migrations.js
async function up({ context: { queryInterface, schema } }) {
  await queryInterface.bulkInsert({ tableName: 'roles', schema }, [
    {
      id: 'admins',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 'managers',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 'members',
      created_at: new Date(),
      updated_at: new Date(),
    },
  ]);
}

async function down({ context: { queryInterface, schema } }) {
  await queryInterface.bulkDelete({ tableName: 'roles', schema }, null, {});
}

module.exports = { up, down };
```

**Comment by mario-lemes** [comment]
Hi @mmkal,

Oh, thanks for pointing that out! For some reason I thought that was not possible, I did the changes that you mentioned but still does not work as expected.

Basically happens what I described in my previous post.

Thanks for taking the time to take a look at this. Really appreciated.

**Comment by mario-lemes** [comment]
Hi again,

I have been getting deeper on the `SequelizeStorage` to see where the problem is coming from and I have some thoughts about it.

It seems there is a function [`getModel()`](https://github.com/sequelize/umzug/blob/2e0766da59e5bf39bf2295d24958eec1986306ae/src/storage/sequelize.ts#L124) which is in charge to return the `SequelizeMeta` model and what happens here is basically that checks if the model exist by using `this.sequelize.isDefined(this.modelName)` which actually checks its existence by lookin into the `sequelize.models` object. 

From sequelize.js:
```
  /**
   * Checks whether a model with the given name is defined
   *
   * @param {string} modelName The name of a model defined with Sequelize.define
   *
   * @returns {boolean} Returns true if model is already defined, otherwise false
   */
  isDefined(modelName) {
    return !!this.modelManager.models.find(model => model.name === modelName);
  }
```

This is totally fine when there is no schema-based approach like in a multi-tenant architecture, hence Sequelize also support other db engines we can check if a model has been defined by checking the `sequelize.models` object. However, this can run into wrong assumptions when we are in a schema-based approach like in `postgres` db, because Sequelize will save internally the models definitions for the first tenant but that does not mean that is actually defined (synced) for the second tenant onwards.

Correct me if I'm wrong but I think the function [`getModel()`](https://github.com/sequelize/umzug/blob/2e0766da59e5bf39bf2295d24958eec1986306ae/src/storage/sequelize.ts#L124) should check the existence of the `SequelizeMeta` model having in consideration the schema-based approach by using a raw query to either the ` information_schema.tables` or `pg_class` and `pg_namespace`, more info [here](https://stackoverflow.com/a/24089729).

Hope all this helps. 

Thanks

**Comment by mmkal** [comment]
Sequelize storage is supposed to be multi-dialect so not really workable to put postgres-specific sql in there.

You might not need to though. AFAIK each sequelize instance has its own model manager, so likely your problem is coming from using a shared sequelize instance. It's hard to tell for sure from your sample code, but it looks like `sequelize` comes from out of scope. Try changing it so that each schema gets its own instance:

```diff
async function runMigration(schema) {
+     const sequelize = new Sequelize (..., { schema });
      const umzug = new Umzug({
        migrations: { glob: 'migrations/*.js' },
        context: sequelize.getQueryInterface(),
        storage: new SequelizeStorage({
          sequelize,
          schema
        }),
      });

      await umzug.up();
}
```

See [sequelize constructor docs](https://sequelize.org/master/class/lib/sequelize.js~Sequelize.html) for how to pass it in.

In fact, assuming that works, by passing the schema into the sequelize constructor, you likely wouldn't need to inject it into the context anymore - I expect it'd be the default schema for the queryInterface object.

**Comment by mario-lemes** [comment]
Hey @mmkal,

That's right, it's a shared instance that is initialized on booting. 

I address the queries by using the schema parameter like `Model.findAll(...{schema})`.

Don't you think that creating a sequlize instance per tenant is an unnecessary workload taking in considerations the multiple connections are created to the db and the memory that having all the models definitions per tenant migth consume.

I'm wondering if there is a way of doing it just by using a shared instance, but maybe that's actually not the ideal way of using sequlize. 

If you don't mind it will be helpfully to read your thoughts about it.

Thanks.

**Comment by mmkal** [comment]
I wasn't aware of `schema` being a valid option to pass into `Model.findAll`.

Sequelize docs do recommend using a shared instance - but in this case you may be ok with using multiple, depending on how long they're used for, how pooling is configured, and how many schemas you need to migrate. Usually migrations are run separately from application code, so hopefully each instance could tear itself down fairly quickly. Definitely worth testing out though.

If you can find a way to explicitly pass the schema to the various calls in SequelizeStorage, a PR would be welcome. I'm planning on adding an examples directory soon, and it'd be good to be able to include this use-case.

**Comment by mario-lemes** [comment]
Hey @mmkal, 
Thanks for your quick response.

I think that's a good point, I can just create the instance for the migration process and close the connection using `sequelize.close()`, that would be good enough for the time being.

In another hand, I'm still interested in getting my hands on the SequelizeStorage in order to make it works just using a sequelise shared instance, so I'll take some time this week to work on it so hopefully, I will be able to send a PR for evaluation.

It would be great if other people can give their thoughts about it but it's up to you to keep this thread open as long as you want, I'm very grateful for the information given so to me it's crystal clear ;).

PS: This sounds interesting [](https://npmjs.com/package/@slonik/migrator), I will take a look to slonik, thanks for sharing!
