### ISSUE TITLE
Committing a transaction results in ending the current migration

### ISSUE THREAD

**Issue by giovanni-bertoncelli** [sequelize/umzug#420]
I have this strange behaviour inside a migration of mine that holds multiple transaction inside. Whenever a transaction inside the migration gets committed Unzug appears to consider the entire migration successfully finished and walks directly to the next migration file.
This behaviour appears also when I wrap all the transactions inside another one for the whole migration file.

I do not know if this is the expected behaviour or not since I've not found anything about transactions in the documentation.

**Comment by mmkal** [comment]
@giovanni-bertoncelli did you mean to close this?

**Comment by giovanni-bertoncelli** [comment]
Yes, sorry, my bad.

**Comment by mmkal** [comment]
Let me know if you need me to reopen. As for the problem you're seeing - can you reproduce it with a small runnable example? Are you using v2 or v3-beta?
