### ISSUE TITLE
Incorrect Storage Type

### ISSUE THREAD

**Issue by blakemorgan** [sequelize/umzug#433]
**Umzug Version**: 2.3.0
**Storage**: Custom
**Node Version**: 14.5.4
**TypeScript Version**: 4.1.3

When instantiating a new Umzug object and providing third-party story from an external package, you get the following error: `Type '"package-name"' is not assignable to type '"json" | "sequelize" | "mongodb" | Storage'.` Since [the documentation](https://github.com/sequelize/umzug/tree/v2.x#method-2-require-external-module-from-npmjscom) says users can "pass the name of the module to the configuration", the `storage` option should accept accept strings: `"json" | "sequelize" | "mongodb" | Storage | string`

My current work around is putting `// @ts-ignore` on the line before the `storage` property, but I'd rather not have to do that since I am using the object correctly.

**Comment by mmkal** [comment]
v3 is now out of beta, so v2 won't be getting any updates other than critical security fixes: https://github.com/sequelize/umzug/releases/tag/v3.0.0 

In v3 the params only accept a storage instance, not a string.
