### ISSUE TITLE
Migrations with relations failing with "relation 'table' does not exist"

### ISSUE THREAD

**Issue by gRoberts84** [sequelize/umzug#44]
Hi there,

When attempting to create a table via migrations which references a table that does not exist yet, it fails with the "relation 'table' does not exist".

I understand that when handling this directly via the database, the same issue would occur, however I would have thought that Sequelize would handle that automatically?

    foreignKeyId: {
        type: Sequelize.INTEGER,
        references: {
            model: 'ForeignTable',
            key: 'id'
        }
    }

For clarity, is it expected for users to generate their table schema without relations first and then create additional migrations containing the relations afterwards or should this work?

Within my model it self, I do have

    associate: function(models) {
        // associations can be defined here
        models.Primary.hasOne(models.Foreign);
    }

Does this handle relations within the database, or does it only define the relationship within Sequelize?

Thanks

**Comment by jukkah** [comment]
Yep, you need to create models first and then add assosiations within the `associate`.

> Creating an association will add a foreign key constraint to the attributes. All associations use CASCADE on update and SET NULL on delete, except for n:m, which also uses CASCADE on delete.

[Sequelize documentation](http://docs.sequelizejs.com/en/latest/api/associations/?highlight=associate) tells that it will create DB level association.

**Comment by jukkah** [comment]
Closing old issue.
