### ISSUE TITLE
Docs: `extend` instructions out of date

### ISSUE THREAD

**Issue by jearangoo** [sequelize/umzug#441]
Version: 3.0.0-beta.15
Storage: memoryStorage
Node: 15.8.0
TypeScript: 4.1.4

hello, i am trying to set a function to sort the migrations files names as specified in the readme

```
const { Umzug } = require('umzug');

const umzug =
  new Umzug({
    migrations: { glob: 'migrations/**/*.js' },
    context: sequelize.getQueryInterface(),
  })
  .extend(migrations => migrations.sort((a, b) => b.path.localeCompare(a.path)))
```
but in typescript it seems like the types are wrong, because the migrations array is readonly so it does not allow to call migrations.sort

https://github.com/Microsoft/TypeScript/issues/17291

this is the definition from node_modules/umzug/lib/umzug.d.ts:72
```
extend(transform: (migrations: ReadonlyArray<RunnableMigration<Ctx>>) => Promisable<Array<RunnableMigration<Ctx>>>): Umzug<Ctx>;
```
maybe the migrations array sould not be readonly? i am getting this error when i try to sort

```
const umzug:Umzug=new Umzug({
	storage:memoryStorage(),
	migrations:{
		glob:'/migrations/*.js'
	},
	logger:console
})
.extend(
	(migrations:readonly RunnableMigration<any>[])=>{
		return migrations.sort((a:RunnableMigration<any>,b:RunnableMigration<any>)=>b.path?.localeCompare(a.path!));
	}
);


TS2339: Property 'sort' does not exist on type 'readonly RunnableMigration []'.
```

**Comment by mmkal** [comment]
@jearangoo ah yes, looks like the readme is out of sync. As a workaround you can `slice()` the array first:

```diff
const umzug:Umzug=new Umzug({
	storage:memoryStorage(),
	migrations:{
		glob:'/migrations/*.js'
	},
	logger:console
})
.extend(
	(migrations:readonly RunnableMigration<any>[])=>{
-		return migrations.sort((a:RunnableMigration<any>,b:RunnableMigration<any>)=>b.path?.localeCompare(a.path!));
+		return migrations.slice().sort((a:RunnableMigration<any>,b:RunnableMigration<any>)=>b.path?.localeCompare(a.path!));
	}
);
```

**Comment by jearangoo** [comment]
thanks

**Comment by mmkal** [comment]
`.extend` has now been removed in favour of creating a new instance directly. See https://github.com/sequelize/umzug/commit/2911d20d936cfebe2167e1b501d1d02138ccf50c for explanation and how to migrate code that uses `.extend` (will be released in the next beta version)
