### ISSUE TITLE
How to use custom tsconfig.json for typescript migrations?

### ISSUE THREAD

**Issue by gvlasov** [sequelize/umzug#444]
In my project I have custom import paths and I want to use the same paths in my migrations. I imagine the way to do that is to use the same tsconfig.json when compiling Umzug migrations as in the rest of my project. But I couldn't find a way to do so. Is there a way?

I'm using umzug 2.3

**Comment by Flashrob** [comment]
To work around this, I run tsc on every migration first and will run the migrations on the compiled js output

**Comment by mmkal** [comment]
v3 is now out of beta, so v2 won't be getting any updates other than critical security fixes: https://github.com/sequelize/umzug/releases/tag/v3.0.0

There are plenty of typescript examples in https://github.com/sequelize/umzug/tree/master/examples. You could either use ts-node, which you won't really want to do in production; compile typescript files into javascript, targeting your migrations folder; or just write javascript migrations. My team use umzug to write majority `.sql` migrations (not using sequelize) and have a smaller number of vanilla javascript ones. No typescript.
