### ISSUE TITLE
Umzug doesnt terminate after running migrations when sequelize pool has 5 as minimum number of connections

### ISSUE THREAD

**Issue by shravan-balasubramanian** [sequelize/umzug#445]
- Umzug version - 2.3.0
- SequelizeStorage
- Sequelize version - 5.19.2
- Node version - 10.16
- Vanilla common js
- Repro steps
   - Instantiate sequelize with pool params as such 
   ```
        pool: {
            min: 5,
            max: 20,
            idle: 60000,
            acquire: 60000
        }
   ```
       
   - Run migrations
   - It keeps running and does not terminate

**Comment by Logan-47** [comment]
@shravan-balasubramanian did you find any solution for this?

**Comment by mmkal** [comment]
v3 is now out of beta, so v2 won't be getting any updates other than critical security fixes: https://github.com/sequelize/umzug/releases/tag/v3.0.0

Feel free to open a new issue linking to this one if you find this still happens in the new version.
