### ISSUE TITLE
Database Migration said rollback but command still executed and not rolledback

### ISSUE THREAD

**Issue by FauziFadhi** [sequelize/umzug#454]
Umzug version : 3.0.0-beta.15
node version 12.x
sequelize-typescript: ^1.1.0
sequelize: ^5.22.3
typescript
storage: SequelizeStorage

i was trying to use umzug as database migration, and I was trying to use transaction that if any failed migration it would roll back.

but when I throw an error after few migration it didn't rollback and runner migration still create the command.

1. i runned this migration
![image](https://user-images.githubusercontent.com/22959762/114361482-5ea6e280-9ba0-11eb-8599-e6bcae6d8a47.png)
code: 
`export const up: Migration = async ({
  context: queryInterface,
}) => {

  await queryInterface.sequelize.transaction(async (transaction) => {
    await queryInterface.addColumn('user_activity', 'ref_id', {
      type: DataType.INTEGER,
    }, { transaction })

    await queryInterface.addColumn('user_activity', 'ref_type', {
      type: DataType.ENUM(...Object.values(ENUM_USER_ACTIVITY_TYPE)),
    }, { transaction })

    await queryInterface.addColumn('user_activity', 'date_time', {
      type: DataType.DATE,
    }, { transaction })

    await queryInterface.addColumn('user_activity', 'exercises_json', {
      type: DataType.JSON,
    }, { transaction })

    await queryInterface.addColumn('user_activity', 'exercise_styles_json', {
      type: DataType.JSON,
    }, { transaction })

    await queryInterface.addColumn('user_activity', 'instructors_json', {
      type: DataType.JSON,
    }, { transaction })
    throw Error()

    await queryInterface.addColumn('user_activity', 'title', {
      type: DataType.STRING,
    }, { transaction })

    await queryInterface.addColumn('user_activity', 'slug', {
      type: DataType.STRING,
    }, { transaction })

    await queryInterface.addColumn('user_activity', 'description', {
      type: DataType.TEXT,
    }, { transaction })

    await queryInterface.addColumn('user_activity', 'image', {
      type: DataType.STRING,
    }, { transaction })

    await queryInterface.addColumn('user_activity', 'duration', {
      type: DataType.INTEGER,
    }, { transaction })

    await queryInterface.addColumn('user_activity', 'intencity', {
      type: DataType.ENUM(...Object.values(ENUM_INTENCITY)),
    }, { transaction })

    await queryInterface.addColumn('user_activity', 'start_time', {
      type: DataType.TIME,
    }, { transaction })

    await queryInterface.addColumn('user_activity', 'end_time', {
      type: DataType.TIME,
    }, { transaction })

    await queryInterface.addColumn('user_activity', 'date', {
      type: DataType.DATEONLY,
    }, { transaction })

    await queryInterface.addColumn('user_activity', 'type', {
      type: DataType.ENUM(...Object.values(ENUM_CLASS_TYPE)),
    }, { transaction })

  })

};`
2. its said rollback 
![image](https://user-images.githubusercontent.com/22959762/114361628-872edc80-9ba0-11eb-9205-0df9cc73748d.png)

3. but the migration not roll back
![image](https://user-images.githubusercontent.com/22959762/114361657-9150db00-9ba0-11eb-8adf-be042ecc9f13.png)

is it bug or im doing it wrong ?

**Comment by mickhansen** [comment]
Only a few RDBMS' support transactional DDLs. It looks like you're using MySQL, which does not support it (last i checked).

**Comment by FauziFadhi** [comment]
> Only a few RDBMS' support transactional DDLs. It looks like you're using MySQL, which does not support it (last i checked).

oh okay, thanks for you information. i will try to get more information with transactional ddls
