### ISSUE TITLE
Add context to migrator._types

### ISSUE THREAD

**Issue by adrienduchemin** [sequelize/umzug#456]
Hi,

It would be super handy to have access to the context type : 
`function myCustomStorage(): UmzugStorage<typeof migrator._types.context>`

It just needs to be added to the types alongside migration : 
`readonly _types: {
        migration: (params: MigrationParams<Ctx>) => Promise<unknown>;
        context: Ctx;
    };`

I can send a PR if you prefer.

Thanks !

**Comment by mmkal** [comment]
I'd be open to this, feel free to make a PR.

**Comment by adrienduchemin** [comment]
Linked to https://github.com/sequelize/umzug/pull/464
