### ISSUE TITLE
Ignore migration file extension in v2

### ISSUE THREAD

**Issue by franciscohanna92** [sequelize/umzug#461]
Hello! Thanks for this awesome package.

Is there any way to ignore the file extension when matching the migration names? 

My use case for this is that we work with a remote dev database instance, where migrations get executed after transpiling them from Typescript. This results in the `SequelizeMeta` table having entries that end up with the `.js` extension. If I want to run a migration from my dev environment, it identifies the migration with the `.ts` extension so it tries to run it again, yielding an error because the table already exists (give that the migration creates a table)

If this is not supported, my idea is to have an option on the constructor which ignores the extension while resolving the migrations and that the entries in the `SequelizeMeta` table don't have it either.

**Comment by fwh1990** [comment]
Maybe not an issue, for customize, try this way 
https://github.com/qoq-ts/qoq-sequelize/blob/master/src/migration/createUmzug.ts#L21

**Comment by giulianoSev** [comment]
I made a custom storage to accomplish this...

```typescript
const umzug = new Umzug({
  migrations: {
    path: path.join(__dirname, 'migrations'),
    params: [sequelize.getQueryInterface()],
    pattern: /^\d+/,
  },
  storage: {
    logMigration: async (name) => {
      const migrationName = name.replace(/\.\w*$/, '');
      await runLiteralQuery(`INSERT INTO dbo.SequelizeMeta VALUES ('${migrationName}')`);
      console.log(`Migrated: ${migrationName}`);
    },
    unlogMigration: async (name) => {
      const migrationName = name.replace(/\.\w*$/, '');
      await runLiteralQuery(`DELETE FROM dbo.SequelizeMeta WHERE name = '${migrationName}'`);
      console.log(`Reverted: ${migrationName}`);
    },
    executed: async () => {
      const [migrations] = await runLiteralQuery<{name: string}>('SELECT * FROM dbo.SequelizeMeta');
      return [
        ...migrations.map(({name}) => name + '.js'),
        ...migrations.map(({name}) => name + '.ts'),
      ];
    },
  },
});
```

**Comment by mmkal** [comment]
Glad you could find a solution. Just a note - it's unlikely that `migrationName` would have any special characters, but as a best practice you should use [replacements or bind parameters](https://sequelize.org/master/manual/raw-queries.html#replacements) when using `sequelize.query` rather than formatting the string in directly.

**Comment by juanmav** [comment]
I know I'm very late to this and what I'm going to comment is for v3. However, I hope this would save some time to the next person with the same problem as me.

```ts
import { Umzug, SequelizeStorage } from 'umzug';

export class CustomSequelizeStorage extends SequelizeStorage {
  async logMigration({ name }: { name: string }) {
    const newName = name.replace(/\.[jt]s$/, ''); // remove .js or .ts extension
    return super.logMigration({ name: newName });
  }

  async unlogMigration({ name }: { name: string }) {
    const newName = name.replace(/\.[jt]s$/, ''); // remove .js or .ts extension
    return super.unlogMigration({ name: newName });
  }
}
```

**Comment by zN3utr4l** [comment]
if you have previously applied migrations in js and now work with ts

```js
class JsToTsSequelizeStorage extends SequelizeStorage {
  async logMigration({ name }: { name: string }) {
    return await super.logMigration({ name: name.replace(/\.[jt]s$/, '') })
  }

  async unlogMigration({ name }: { name: string }) {
    return await super.unlogMigration({ name: name.replace(/\.[jt]s$/, '') })
  }

  async executed() {
    const migrations = (await super.executed()).map(name => name.replace(/\.[jt]s$/, ''))
    return [
      ...migrations.map(name => name + '.js'),
      ...migrations.map(name => name + '.ts'),
    ]
  }
}
```
