### ISSUE TITLE
Error: Expected to be a pending migration but it wasn't

### ISSUE THREAD

**Issue by zefexdeveloper** [sequelize/umzug#468]
I'm getting this error `Error: Expected database\migrations\2021.05.30T14.14.38.create_users_table.ts to be a pending migration but it wasn't! You should investigate this. Use --skip-verify to bypass this error.` whenever I use `create`. I'm using the https://github.com/sequelize/umzug/tree/master/examples/4.sequelize-seeders as reference.

What can it be? It's creating the migration table on my database tho, but it's empty.

**Comment by mmkal** [comment]
This usually means you have a glob pattern pointing at the wrong directory. If you could share the options you're passing to the constructor it might be possible to see what's wrong. Or, even better, a git repo/branch which reproduces the error.

**Comment by zefexdeveloper** [comment]
```typescript
import { Umzug, SequelizeStorage } from 'umzug'
import { Sequelize } from 'sequelize'

import databaseConfig from '../database/config'

const sequelize = new Sequelize(databaseConfig)

const context = {
  sequelize
}

export const migrator = new Umzug({
  migrations: {
    glob: ['database/migrations/*.ts', { cwd: __dirname }]
  },
  context,
  storage: new SequelizeStorage({
    sequelize,
    modelName: 'migrations'
  }),
  logger: console
})

export const seeder = new Umzug({
  migrations: {
    glob: ['database/seeders/*.ts', { cwd: __dirname }]
  },
  context,
  storage: new SequelizeStorage({
    sequelize,
    modelName: 'seeders'
  }),
  logger: console
})

export type Migration = typeof migrator._types.migration
export type Seeder = typeof seeder._types.migration

```

The thing is that when using `create` it does create the migration.

**Comment by zefexdeveloper** [comment]
cc @mmkal I created a repository with the problem, the usage is on the readme: https://github.com/zefexdeveloper/umzug-problem

**Comment by mmkal** [comment]
In that repo, you've set `cwd: __dirname` which means it's looking for files matching `database/seeders/*.ts` in the `cli/` directory. If you get rid of the `cwd` parameter or use `path.join(__dirname, '..')` to be explicit it should work.

**Comment by zefexdeveloper** [comment]
It worked, thank you very much. I thought as I was running the command on the root dir it would start from there.

One last question: why do I have to specify `--folder` when running `create` as the directory is already specified in the config? Thank you again.

**Comment by mmkal** [comment]
1. Since all you do is specify a glob, there isn't necessarily a single "folder" umzug can know to put the _first_ migration in. Once you've created one, though, it will assume you want to create the next in the same folder. So it's ok to pass `--folder` in via CLI the first time, you won't have to for the second.
2. No, using `ts-node` directly is pretty much equivalent to using `ts-node/register`. The only downside is you can't just look at the code to see how it works - it needs to be run with a special script. As long as that's documented in your project that's fine though.
