### ISSUE TITLE
Running migrations in single transaction

### ISSUE THREAD

**Issue by jalorenz94** [sequelize/umzug#484]
Hi everyone,

first of all, thanks a lot for the library :) Is there any chance to run the pending migrations `umzug.up()` in a single transaction? Currently, i build some logic around it, with the drawback that i have to remove the processed migrations from the `SequelizeMeta` table when the transaction was roll backed.

**Comment by mmkal** [comment]
This can be done with the `'beforeCommand'`/`'afterCommand'` events, but locking varies pretty widely between databases so it might be tricky to do via sequelize. [@slonik/migrator](https://npmjs.com/package/@slonik/migrator) is postgres-only, based on umzug and allows running all migrations in a single transaction this way.
