### ISSUE TITLE
SequelizeMeta deleting last entry

### ISSUE THREAD

**Issue by peaverok** [sequelize/umzug#496]
I am running migrations using the latest beta v3.0.0-beta.16.

The SequelizeMeta table is missing the last entry.

The last lines of my logging is this:
2021-09-06 13:52:52:5252 debug: Executing (default): SELECT "name", "createdAt", "updatedAt" FROM "SequelizeMeta" AS "SequelizeMeta" ORDER BY "SequelizeMeta"."name" ASC;
{ event: 'reverting', name: '6-airports.ts' }
2021-09-06 13:52:52:5252 debug: Executing (default): CREATE TABLE IF NOT EXISTS "SequelizeMeta" ("name" VARCHAR(255) NOT NULL UNIQUE , "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("name"));
2021-09-06 13:52:52:5252 debug: Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'SequelizeMeta' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
2021-09-06 13:52:52:5252 debug: Executing (default): DELETE FROM "SequelizeMeta" WHERE "name" = '6-airports.ts'
{ event: 'reverted', name: '6-airports.ts', durationSeconds: 0.011 }
Connection established and migrations run.

Notice the last entry:
 DELETE FROM "SequelizeMeta" WHERE "name" = '6-airports.ts'

My migration script "6-airports.ts" works fine. No errors and the data I created in the up method is present in the database. My actual migrations are working fine, it just seems to think the last entry doesn't work and deletes it.

Note that this happens every time no matter how many migration scripts I run. I have 6 (ending in 6-airports.ts). If I only run the first 3 then I only get 2 entries in SequelizeMeta. If I run the first 4, I get 3 entries in SequelizeMeta, etc.

It seems to think the last script fails every time.

Here is the logging for the 6-airport.ts script indicating it is fine:
C:\DevProjects\node-module-before-faa\src\sequelize\migrations\m1-seed\6-airports.ts
<ref *2> PostgresQueryInterface {
  sequelize: <ref *1> Sequelize {
    options: {
      dialect: 'postgres',
      dialectModule: null,
      dialectModulePath: null,
      host: '127.0.0.1',
      protocol: 'tcp',
      define: {},
      query: {},
      sync: {},
      timezone: '+00:00',
      clientMinMessages: 'warning',
      standardConformingStrings: true,
      logging: [Function: logging],
      omitNull: false,
      native: false,
      replication: false,
      ssl: undefined,
      pool: [Object],
      quoteIdentifiers: true,
      hooks: {},
      retry: [Object],
      transactionType: 'DEFERRED',
      isolationLevel: null,
      databaseVersion: '13.4.0',
      typeValidation: false,
      benchmark: false,
      minifyAliases: false,
      logQueryParameters: false,
      username: 'postgres',
      password: 'xxxxx!',
      database: 'xxxxx',
      port: 5432
    },
    config: {
      database: 'xxxxx',
      username: 'postgres',
      password: 'xxxxx!',
      host: '127.0.0.1',
      port: 5432,
      pool: [Object],
      protocol: 'tcp',
      native: false,
      ssl: undefined,
      replication: false,
      dialectModule: null,
      dialectModulePath: null,
      keepDefaultTimezone: undefined,
      dialectOptions: undefined
    },
    dialect: PostgresDialect {
      sequelize: [Circular *1],
      connectionManager: [ConnectionManager],
      queryGenerator: [PostgresQueryGenerator],
      queryInterface: [Circular *2]
    },
    queryInterface: [Circular *2],
    models: {
      Airport: Airport,
      Permission: Permission,
      RefreshToken: RefreshToken,
      RolePermission: RolePermission,
      Role: Role,
      UserRole: UserRole,
      User: User,
      SequelizeMeta: SequelizeMeta
    },
    modelManager: ModelManager { models: [Array], sequelize: [Circular *1] },
    connectionManager: ConnectionManager {
      sequelize: [Circular *1],
      config: [Object],
      dialect: [PostgresDialect],
      versionPromise: null,
      dialectName: 'postgres',
      pool: [Pool],
      lib: [PG],
      nameOidMap: [Object],
      enumOids: [Object],
      oidParserMap: [Map]
    }
  },
  queryGenerator: <ref *3> PostgresQueryGenerator {
    sequelize: <ref *1> Sequelize {
      options: [Object],
      config: [Object],
      dialect: [PostgresDialect],
      queryInterface: [Circular *2],
      models: [Object],
      modelManager: [ModelManager],
      connectionManager: [ConnectionManager]
    },
    options: {
      dialect: 'postgres',
      dialectModule: null,
      dialectModulePath: null,
      host: '127.0.0.1',
      protocol: 'tcp',
      define: {},
      query: {},
      sync: {},
      timezone: '+00:00',
      clientMinMessages: 'warning',
      standardConformingStrings: true,
      logging: [Function: logging],
      omitNull: false,
      native: false,
      replication: false,
      ssl: undefined,
      pool: [Object],
      quoteIdentifiers: true,
      hooks: {},
      retry: [Object],
      transactionType: 'DEFERRED',
      isolationLevel: null,
      databaseVersion: '13.4.0',
      typeValidation: false,
      benchmark: false,
      minifyAliases: false,
      logQueryParameters: false,
      username: 'postgres',
      password: 'xxxxx',
      database: 'xxxxx',
      port: 5432
    },
    dialect: 'postgres',
    _dialect: PostgresDialect {
      sequelize: [Sequelize],
      connectionManager: [ConnectionManager],
      queryGenerator: [Circular *3],
      queryInterface: [Circular *2]
    },
    typeValidation: undefined
  }
}
{ up: [Function: up], down: [Function: down] }

**Comment by peaverok** [comment]
Hmm. Seems if I call both up and down this is happening:

await umzug.up();
await umzug.down();

Currently all my downs are empty but for later migrations I may have some. 

I think I have it figured out but it makes no sense. I call umzug.up() for my up methods but umzug.down() automatically does stuff even though my down methods are all empty? Why does it not call all of the down methods in my migration scripts in the reverse order as the up methods (and since they are empty do nothing)? Why would it do ANYTHING other than try to call all of the down methods in my migration scripts by default in reverse order? Options are fine but the default makes no logical sense whatsoever and doesn't match the default of the up method!

**Comment by peaverok** [comment]
I am going to close it but I think this should be changed. The up and down methods should make logical sense in how they work in correlation to each other.

**Comment by mmkal** [comment]
I'm not sure there's _any_ safe default behaviour if you inconsistently implement down migrations. What if one migration creates a table, and another adds a column to it? I would either implement them for every migrations, or avoid using them completely.
