### ISSUE TITLE
revert last migration - reverts all if param is empty object

### ISSUE THREAD

**Issue by mitjacotic** [sequelize/umzug#50]
Since introduction of `to: 0` to revert all migrations I think a bug was introduced;

``` javascript
umzug.down({}).then(function (migration) {
   // will be same as using {to: 0} i.e. will revert ALL migrations
});
```

using `undefined` as params works as expected. If this is intentional, I think readme should be updated so users will know of this as well.

**Comment by jukkah** [comment]
I think `{}` is almost equal to `{to: falsyValue}`. IMHO is that we don't need to exactly specify this in the documentation. However passing an empty object instead of nothing may indicate that there is a bug somewhere (or programmer is lazy :smile:). But allowing it makes umzug more flexible.

BTW `up()` runs all the migrations but `down()` reverts only the latest one.

**Comment by mitjacotic** [comment]
Lazy no, it was more like setting up the option object (because I was thinking that there might come more params/opts in the future). So I was always sending the options into the up/down calls and was flabbergasted when it reverted all the migrations after umzug upgrade. I thought it's a bug, but I think this behaviour surely is not what somebody expects after reading the docs:)

**Comment by tremby** [comment]
This just bit me too. I was setting options to an empty object, and then in certain conditions adding `to: 0` to that object. But it's reverting all migrations regardless. Very glad I didn't first encounter this in a production environment! In my mind this is most definitely a bug. Certainly isn't lazy programming in my case. If the `to` key doesn't exist at all it should obviously be treated as default, which the docs clearly say is to only revert one single migration.

**Comment by jukkah** [comment]
Now, I'm thinking this once again. You guys are right. `down({}) != down({to: 0})`. It can't be considered valid so there are two options available: a) throw an error or b) consider nothing (valid) has been passed. I vote for last one.

**Comment by tremby** [comment]
Yeah, to me, an empty object means "default options". It's a normal pattern to have a passed options object merged in to a default options object behind the scenes. That's what I expected here.

**Comment by sdepold** [comment]
Fixed in 1.9.1

**Comment by jukkah** [comment]
I'm designing v2.0 and this will be fixed in it.

**Comment by mmkal** [comment]
Fixed by https://github.com/sequelize/umzug/pull/231
