### ISSUE TITLE
Typos in Es modules example

### ISSUE THREAD

**Issue by cellulosa** [sequelize/umzug#500]
It should be `getModule()).down(downParams)` in https://github.com/sequelize/umzug/blob/ad50a474bf872480786d48e60e08f03427a9386f/examples/2.es-modules/umzug.mjs#L24

Also `import.meta.url.replace('file:///', '/')` in https://github.com/sequelize/umzug/blob/ad50a474bf872480786d48e60e08f03427a9386f/examples/2.es-modules/umzug.mjs#L16

**Comment by mmkal** [comment]
Thank you! Would you like to open a PR to fix?

**Comment by cellulosa** [comment]
> Thank you! Would you like to open a PR to fix?

done ;)
