### ISSUE TITLE
Generated migrations have empty `up` and `down` functions

### ISSUE THREAD

**Issue by brianreeve** [sequelize/umzug#520]
- Version: umzug@3.0.0-beta.16
- Storage: SequelizeStorage
- Sequelize Version: 6.7.0
- Node v14.17.6
- Vanilla JS

I am starting a new project and would like to use the latest sequelize and umzug beta and take advantage of CLI migration generation and execution. I haven't used prior versions, but the packages look like a good fit.

When I add or modify a model, then generate a migration using the `create` sub command, I get a migration file with empty `up` and `down` methods.

```bash
node ./scripts/migrator.js create --name migration.js --folder migrations/
```

yields:

```javascript
// <datestamp>.migration.js`

/** @type {import('umzug').MigrationFn<any>} */
exports.up = async params => {};

/** @type {import('umzug').MigrationFn<any>} */
exports.down = async params => {};
```

I'm happy to share more implementation details (my `migrator.js` CLI entrypoint, model(s), etc.), but maybe I'm missing something. The README doesn't explicitly state intended behavior.

Is the intended output just limited to providing a sequential filename and bare template for the developer to fill in manually, or is there some level of introspection and query generation?

**Comment by ahmdsolmn** [comment]
Hi @brianreeve, currently the intended output just limited to providing a sequential filename and bare template for the developer to fill in manually. There was a [package](https://github.com/flexxnn/sequelize-auto-migrations) that did this but I believe it is no longer maintained.

**Comment by mmkal** [comment]
@brianreeve yes, this is intended behaviour. Umzug is a genera-purpose migration tool, so it doesn't assume that you're going to be creating sequelize models rather than some other format. This is documented, along with instructions for providing your own project-specific template, in the readme here: https://github.com/sequelize/umzug#creating-migrations---cli
