### ISSUE TITLE
Instead of using `emit` can we use `emitSerial` to have the listeners be awaited in order?

### ISSUE THREAD

**Issue by ahmetsevki** [sequelize/umzug#525]
Umzug version: umzug@3.0.0-beta.15
storage: custom, SlonikMigrator (@slonik/migrator)

SlonikMigrator uses `on('beforeCommand')` to create the table that stores the migrations. But because Umzug emits the events using `emit`, they are awaited concurently. Our application which uses SlonikMigrator (or any custom storage) also uses `beforeCommand` to do some sql as well. However, due to concurrency of the listeners,  the order of execution of sql commands that we register in app and slonik-migrator registers is non-deterministic.

https://github.com/sindresorhus/emittery#emiteventname-data
>  Trigger an event asynchronously, optionally with some data. Listeners are called in the order they were added, but executed concurrently.

> Returns a promise that resolves when all the event listeners are done. Done meaning executed if synchronous or resolved when an async/promise-returning function. You usually wouldn't want to wait for this, but you could for example catch possible errors. If any of the listeners throw/reject, the returned promise will be rejected with the error, but the other listeners will not be affected.

There are other uses, for instance, `migrated` event can be used to automatically add `created_at`, `updated_at` fields or whatever application specific needs arise. It is important that they run in serial.

Suggestion: use `emitSerial` instead of `emit`

**Comment by mmkal** [comment]
This was more of an issue with the weird way that slonik-migrator was using events. Neither slonik nor umzug now add any event listeners, so you can run your event callback(s) however you like now.
