### ISSUE TITLE
CLI create: "Expected to be a pending migration but it wasn't!" when using create.template name transformation

### ISSUE THREAD

**Issue by kf6kjg** [sequelize/umzug#559]
Looks like Umzug isn't handling the renaming of the inbound filename terribly well. I could make the "error" go away by adding the flag it mentions, but that just masks the problem.

## Environment

Umzug 3.1.1
SequelizeStorage
Node 16 & 18
TypeScript, CommonJS

## Relevant code snippet

```typescript
	return new Umzug<QueryInterface>({
		context: sequelize?.getQueryInterface(),
		create: {
			folder: migrationsDir,
			template: (filepath): [string, string][] => {
				return [
					[
						`${filepath.toLowerCase()}.m.ts`,
						`import { DataTypes, QueryInterface } from "sequelize";
```

## Example execution
```sh
$ ts-node --files -- src/cli "create" "--name" "asdfQWER"

{
  event: 'created',
  path: 'REDACTED/src/migrations/2022.08.05t21.35.28.asdfqwer.m.ts'
}

Error: Expected REDACTED/src/migrations/2022.08.05T21.35.28.asdfQWER to be a pending migration but it wasn't! You should investigate this. Use --skip-verify to bypass this error.
```

The file gets created, so this is more of a warning than an actual error, but it does cause confusion for the team members.

**Comment by mmkal** [comment]
This warning isn't so much about the file failing to be created, but about it not being picked up by your `migrations.glob` setting (or other `migrations` configuration). After the file is created (and the warning ignored), is it listed by `ts-node --files -- src/cli pending`?

**Comment by kf6kjg** [comment]
It is.

```sh
$ npx ts-node --files -- src/cli "create" "--name" "asdfQWER"
{
  event: 'created',
  path: '/users/rickycurtice/dev_onerail/onerail/packages/lib-template-schema/src/migrations/2022.08.12t19.04.33.asdfqwer.m.ts'
}

Error: Expected /Users/rickycurtice/dev_onerail/onerail/packages/lib-template-schema/src/migrations/2022.08.12T19.04.33.asdfQWER to be a pending migration but it wasn't! You should investigate this. Use --skip-verify to bypass this error.
$ npx ts-node --files -- src/cli pending
2022.06.03T08.13.57.example.m
2022.08.12t19.04.33.asdfqwer.m
```

**Comment by mmkal** [comment]
@kf6kjg fixed in the release above. Note that the code snippet you posted has a bug though and may still snip the error - you are calling `.toLowerCase()` on the whole file path, which might have unexpected behaviour for some users who clone into a path with caps in it (e.g. `/Users/bob/src/yourapp`). You should probably make a change along these lines:

```diff
			template: (filepath): [string, string][] => {
+				const parsed = path.parse(filepath);
				return [
					[
-						`${filepath.toLowerCase()}.m.ts`,
+						`${parsed.dir}/${parsed.base.toLowerCase()}.m.ts`,
						`import { DataTypes, QueryInterface } from "sequelize";

**Comment by kf6kjg** [comment]
Oooh! Excellent catch and excellent that the error is fixed!

Thank you.
