### ISSUE TITLE
Use custom name for migration instead of file name

### ISSUE THREAD

**Issue by tommy5dollar** [sequelize/umzug#586]
Hello and apologies if this is obvious. I've had a read through the docs and any similar sounding issues but can't see anything.

We've been using umzug (via sequelize) for some time and have a decent numbers of migrations executed across multiple environments.

I now want to retrospectively rename a few of the historic migrations (due to them containing characters legal in Linux but not in Windows) but this would lead to them being re-executed upon our next deployment (migration is part of our DevOps flow).

Obviously I could simply change the relevant names in the meta DB table prior to deployment but is there currently a way to specify a custom name for a migration, such as a property alongside the up and down methods?

Thanks in advance for your help!

**Comment by mmkal** [comment]
Yes, this is possible using `migrations.resolve`. Here's an example of something similar: https://github.com/sequelize/umzug#modifying-the-parameters-passed-to-your-migration-methods

**Comment by tommy5dollar** [comment]
Thanks for the help, that definitely looks very helpful.

Maybe it'd be better for me to go ask on the `sequelize/cli` repo at this point but do you know if there's an easy way to pass a resolver through to umzug if we're currently calling it by invoking `npx sequelize db:migrate` configured using a `.sequelizerc` file?

Thanks again!

**Comment by mmkal** [comment]
I'm sorry, I'm not sure about that, sequelize cli is downstream of umzug. But, umzug does have its own CLI which you could try out - might not have all the sequelize-specific features of sequelize-cli but it's pretty flexible. Feel free to try it and open an issue if there are missing features you find.
