### ISSUE TITLE
create options template with async method 

### ISSUE THREAD

**Issue by ccamensuli** [sequelize/umzug#589]
Proposal for   apply async method on template options create

 use version    "3.2.1"

##  Current
``` js
const umzug = new Umzug({
  migrations: ...,
	create: {
		template: filepath => [
			[filepath, fs.readFileSync('path/to/your/template/file').toString()],
		]
	}
})
```

##  Proposal 
``` js
const umzug = new Umzug({
  migrations: ...,
   create: {
	template: async (filepath) => {
              return [
                [filepath,  await this.renderAsync('path/to/your/template/file')]
              ]
          }
   }
})
```

##    src/umzug.ts   
``` ts
 //  maybe  just add await  when call template method 
 const toWrite = await template(filepath);
 if (toWrite.length === 0) {
      toWrite.push([filepath, '']);
  }
```

**Comment by mmkal** [comment]
@ccamensuli  I'd be happy to accept a PR for this. As long as it's backwards compatible - that is, the types should still allow for a synchronous function.

**Comment by ccamensuli** [comment]
@mmkal   I'm a little short of time to implement this feature at the moment, but when I have it I'll be happy to offer you a PR

thank you for the interest
