### ISSUE TITLE
CLI not responding

### ISSUE THREAD

**Issue by redevill** [sequelize/umzug#593]
Yes - several rants, I am afraid:
V2 working nicely. (particularly the command with 'from')

V3 example (sequelize typescript) - specifically the CLI - nothing but headache.

Please include
- the full umzug version you're using - 3.2.1

migrate.js

```
require('ts-node').register({ compilerOptions:  {
    "allowJs": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "baseUrl": "./",
    "declaration": false,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "inlineSourceMap": false,
    "inlineSources": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "noEmit": false,
    "noEmitOnError": true,
    "outDir": "./.ts-node",
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "strict": true,
    "strictNullChecks": true,
    "target": "esnext",
    "useDefineForClassFields": true
  }});
require('./server/umzugas.ts').migrator.runAsCLI();
```

Now I have tried 2 forms of the code - one hard coded options to keep it simple, and another driven off environ specification.

```
import { Sequelize as TSqlz, SequelizeOptions } from 'sequelize-typescript';
import { SequelizeStorage, Umzug } from 'umzug';

const hardOpts: SequelizeOptions = {
  database: 'db_eg',
  dialect: 'mysql',
  username: 'username',
  password: 'password',
  host: 'URL',
  port: 1433,
  pool: {
    max: 5,
    min: 0,
    acquire: 30000,
    idle: 10000
  },
  define: {
    freezeTableName: true,
    timestamps: false
  }
};

let sequelize: TSqlz;

if(hardOpts) {
  sequelize = new TSqlz(hardOpts);
} else {
  throw new Error(`database options could not be fetched`);
}
export const migrator = new Umzug({
    migrations: {
      glob: ['./server/db/migrations/*.ts', { cwd: __dirname }],
    },
    context: sequelize,
    storage: new SequelizeStorage({ sequelize: sequelize }),
    logger: console,
});

export type Migration = typeof migrator._types.migration;

```

This hard coded version simply returns (after the command node migrate pending:
Error: connect ETIMEDOUT

The second version shows some output:

Executing (default): SELECT TABLE_NAME, TABLE_SCHEMA FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME = N'SequelizeMeta' AND TABLE_SCHEMA = N'dbo'
Executing (default): EXEC sys.sp_helpindex @objname = N'[SequelizeMeta]';
Executing (default): SELECT [name] FROM [SequelizeMeta] AS [SequelizeMeta] ORDER BY [SequelizeMeta].[name] ASC;

Pauses - then shows the command prompt.

Any ideas?
Any chance of getting the "From" back in the command? (I have a good usecase)

**Comment by mmkal** [comment]
I suspect this is just a sequelize connection problem. If you can create a minimal repro (ideally that I can run via codespaces with a command like `npm install && npm test`) I'll take a look. Re "from", see my response to your discussion topic: https://github.com/sequelize/umzug/discussions/594

**Comment by redevill** [comment]
Will try and follow up soon... this was a while back and don't remember where we wound up on this...

**Comment by mmkal** [comment]
Closing, I'm using the CLI daily and... it responds! Feel free to open a new issue if you find a repro.
