### ISSUE TITLE
Create tables with schema from sequelize config

### ISSUE THREAD

**Issue by dspintelegence** [sequelize/umzug#600]
When creating tables inside a migration, I have to provide a table name to the `createTable` method. I want the schema to be used automatically when sequelize is configured to be used with umzug and the schema option is set. This is due to the fact that given the environment the schema name might differ in an application. 

It is the most flexible approach, by automatically using the schema name to concat it with the table name. Otherwise the schema name is hardcoded in the migration file.

**Comment by mmkal** [comment]
Is there a way to set the default schema in sequelize? If not, you could always pass it in to your migrations via context. Example of passing in a custom context [here](https://github.com/sequelize/umzug/blob/dddae21f87faa2fe2ac754c192509797e75c7572/test/umzug.test.ts#L27-L33)
