### ISSUE TITLE
Update to V3 of umzug does not appear to have compatible @types/umzug 

### ISSUE THREAD

**Issue by redevill** [sequelize/umzug#603]
Attempting to upgrade to V3.2.1
Sequelize Storage
Sequelize V6.28
Node 16.15.0
Typescript (VERY RELEVANT)

As stated in the title - The typings when trying to use this in Typescript are not up to date with the new release.
Get many errors pointing to e.g. "Migration" interface is not exported. UpDownMigrationsOptions also claims to be missing. While They are plain to see in the index file.

TIA

**Comment by mmkal** [comment]
The external typings should not be used with v3. Just remove the dependency.

**Comment by redevill** [comment]
Just tried what you suggested:
This is the code import statement and below are the compilation errors.

import { Migration, Umzug, UpDownMigrationsOptions } from 'umzug';
*************

Building Node Server
server/db/dbMgmt/ormFactory.ts:3:10 - error TS2724: '"umzug"' has no exported member named 'Migration'. Did you mean 'MigrationFn'?

3 import { Migration, Umzug, UpDownMigrationsOptions } from 'umzug';
           ~~~~~~~~~

server/db/dbMgmt/ormFactory.ts:3:28 - error TS2305: Module '"umzug"' has no exported member 'UpDownMigrationsOptions'.

3 import { Migration, Umzug, UpDownMigrationsOptions } from 'umzug';
                             ~~~~~~~~~~~~~~~~~~~~~~~

server/services/db-admin.handlers.ts:5:10 - error TS2305: Module '"umzug"' has no exported member 'UpDownMigrationsOptions'.

5 import { UpDownMigrationsOptions } from 'umzug';
           ~~~~~~~~~~~~~~~~~~~~~~~

**Comment by redevill** [comment]
FYI - did use the npm ci option to ensure a rebuild of the node modules. Also tried several other V3 tags - V3.2.1 , V3.0.0 and the first beta... all give the same errors.

**Comment by mmkal** [comment]
See the error: `Module '"umzug"' has no exported member 'UpDownMigrationsOptions'.`. This is not an export of v3. I believe it also wasn't an official export of v2 - the types were originally maintained separately - so it's not documented in the migration guide. But, have a look at the readme to make sure you understand the differences between 2 and 3. If you'd like to add a note to the readme a PR would be welcome.

**Comment by redevill** [comment]
Not sure I understand - A primary public function in umzug V2 & V3 -  is the method "up" as defined below:
`up(options?: UpToOptions | UpDownMigrationsOptions): Promise<Migration[]>;`

How am I to create a strongly typed options object "UpDownMigrationsOptions" to pass to the publicly defined method "up" if it is not exported?

**Comment by mmkal** [comment]
No it isn't: https://github.com/sequelize/umzug/blob/10ef28d6f06e4adf661d0596803cc7491ca455a8/src/umzug.ts#L220
