### ISSUE TITLE
Example migration not working

### ISSUE THREAD

**Issue by paul-uz** [sequelize/umzug#605]
Using a migration and model created by the CLI, using the exmaple in the docs, I get an error when trying to run `umzug.up()`

> MigrationError: Migration 20230517141644-create-user.js (up) failed: Original error: Cannot read properties of undefined (reading 'INTEGER')

index.js

```
const sequelize = new Sequelize({ dialect: 'sqlite', storage: './db.sqlite' });

const umzug = new Umzug({
  migrations: { glob: 'migrations/*.js' },
  context: sequelize.getQueryInterface(),
  storage: new SequelizeStorage({ sequelize }),
  logger: console,
});

(async () => {
  await umzug.up();
})();
```

user migration file
```
'use strict';
/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.createTable('Users', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      },
      firstName: {
        type: Sequelize.STRING
      },
      lastName: {
        type: Sequelize.STRING
      },
      email: {
        type: Sequelize.STRING
      },
      createdAt: {
        allowNull: false,
        type: Sequelize.DATE
      },
      updatedAt: {
        allowNull: false,
        type: Sequelize.DATE
      }
    });
  },
  async down(queryInterface, Sequelize) {
    await queryInterface.dropTable('Users');
  }
};
```

**Comment by paul-uz** [comment]
Looks like the CLI tool to generate a model and the corresponding migration is not generating the correct code.

The migration was missing a require to `Sequelize` and the params for `up()` was wrong. It had `async up(queryInterface, Sequelize)` but should be `async up({context:queryInterface})`

**Comment by paul-uz** [comment]
Nvm, needed the new config options

**Comment by GarrettEHill** [comment]
what change was needed to the config to support this?

**Comment by paul-uz** [comment]
> @paul-uz  what change was needed to the config to support this?

Look for the section under "Modifying the parameters passed to your migration methods" in the readme.

**Comment by pkyeck** [comment]
For the people – like me – that searched and found this issue but not the actual solution:

here is the link to the readme: https://github.com/sequelize/umzug#modifying-the-parameters-passed-to-your-migration-methods
