### ISSUE TITLE
SequelizeStorage model uses options that are rejected by sequelize v7 + postgres et al

### ISSUE THREAD

**Issue by chriswheeldon-peakon** [sequelize/umzug#612]
The SequelizeStorage engine is specifying `charset` and `collate` in the table definition options [here](https://github.com/sequelize/umzug/blob/main/src/storage/sequelize.ts#L145). I think these options are meaningless to postgres among others and, since https://github.com/sequelize/sequelize/pull/15846, are now rejected by sequelize with an exception when umzug attempts to synchronise its metadata table.

Versions:
umzug: 3.2.1
Storage: Sequelize
@sequelize/core: 7.0.0-alpha.27 
postgres: 15.2

n.b. it is possible to work around this by passing an already created sequelize model definition to the SequelizeStorage constructor e.g.

```js
new SequelizeStorage({
    model: sequelize.isDefined(tableName)
      ? sequelize.model(tableName)
      : sequelize.define(
          tableName,
          {
            [columnName]: {
              type: DataTypes.STRING,
              allowNull: false,
              unique: true,
              primaryKey: true,
              autoIncrement: false,
            },
          },
          {
            tableName,
            timestamps: false,
            schema,
          }
        ),
  });
```

**Comment by chriswheeldon-peakon** [comment]
As far as I can tell, from the sequelize PR, only the `snowflake` and, through their absence in the PR,  `mariadb` and `mysql` dialects support these options.

**Comment by mmkal** [comment]
Thank you! Maybe we can allow options overrides so v7 users can do something like 

```ts
new SequelizeStorage(..., {
  options: ({charset, collate, ...options}) => options,
})
```

or something like that. 

Then, at some point, v7 could become the default, or another storage could be added for it or something.

**Comment by EinfachHans** [comment]
With latest v7 alpha i get this error:

`Error: The following options are not supported by createTableQuery in postgres: charset, collate`

Setting the values to `undefined` instead of `null` works for me - Should i create a pr?
