### ISSUE TITLE
Breaking change in v3.3.0

### ISSUE THREAD

**Issue by ddolcimascolo** [sequelize/umzug#614]
Hi guys,

Umzug v3.3.0 introduces a breaking change, there's now an `id` column expected in the `migrations` table when using sequelize storage. Running migrations now fail because this column does not exist in the database...

Can you revert this and release a 3.3.1 as soon as possible?

Thx,
David

**Comment by ddolcimascolo** [comment]
@mmkal @GuyEphraim

I'm bringing your attention on this issue. Sorry I don't have much details handy as I'm not at work and only have CI logs, but the problem is pretty obvious by looking at https://github.com/sequelize/umzug/commit/15fc2fedf34c9673919aee7dfdc3dd67eae33ded

Anything I can do to help?

Thx,
David

**Comment by wangshijun** [comment]
Same issue here

**Comment by mmkal** [comment]
Thanks for the report. I will try to publish a revert in the next day or so. In the meantime, please use `3.2.1` (or `~3.2.1`, but not `^3.2.1`).

**Comment by mmkal** [comment]
[3.3.1 released](https://github.com/sequelize/umzug/releases/v3.3.1)

[3.3.0 deprecated](https://www.npmjs.com/package/umzug/v/3.3.0) ([github release edited](https://github.com/sequelize/umzug/releases/v3.3.0))

@mau31415 @GuyEphraim if you would like to un-revert/open a new PR please feel free. In the meantime I may try to write a breaking-change-smoke-test for SequelizeStorage.

**Comment by ddolcimascolo** [comment]
Thx for fixing
