### ISSUE TITLE
`RunAsCLI()` swallows exceptions

### ISSUE THREAD

**Issue by pkit** [sequelize/umzug#619]
It looks like you use [`execute()`](https://github.com/microsoft/rushstack/blob/af0751d3f2e74afeb16fa249755b92b723931abe/libraries/ts-command-line/src/providers/CommandLineParser.ts#L146) from the `ts-command-whatever` library.
Which silently swallows all exceptions by default.
Should be documented probably?

**Comment by mmkal** [comment]
`ts-command-whatever` (excellent name) has a method called `executeWithoutErrorHandling`. I'll look into mapping a CLI arg to it.

**Comment by mmkal** [comment]
Here's something you could do right now:

```ts
import {Umzug, UmzugCLI, CommandLineParserOptions} from 'umzug'

class MyUmzugCLI extends UmzugCLI {
  async execute() {
    await super.executeWithoutErrorHandling()
    return true
  }
}

class MyUmzug extends Umzug {
  getCLI(options?: CommandLineParserOptions) {
    return new MyUmzugCLI(this, options)
  }
}

const myUmug = new MyUmzug(...)

myUmzug.runAsCLI()
```

**Comment by pkit** [comment]
Yep, I've already implemented. 
I can read the other people's code (shocking, I know). Was complaining only about the docs. :)
