### ISSUE TITLE
Do not set charset and collate options on postgresql

### ISSUE THREAD

**Issue by QuentinFarizon** [sequelize/umzug#623]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `umzug@2.3.0` for the project I'm working on.

Sequelize v7.0.0-alpha.33 complains (rightly so), that collate and charset optinos are not supposed to be passed for postgres dialect. To my knowledge, this is only used for mysql

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/umzug/lib/storages/SequelizeStorage.js b/node_modules/umzug/lib/storages/SequelizeStorage.js
index 1277063..469a6cc 100644
--- a/node_modules/umzug/lib/storages/SequelizeStorage.js
+++ b/node_modules/umzug/lib/storages/SequelizeStorage.js
@@ -90,8 +90,8 @@ class SequelizeStorage extends _Storage.default {
       tableName: this.tableName,
       schema: this.schema,
       timestamps: this.timestamps,
-      charset: 'utf8',
-      collate: 'utf8_unicode_ci'
+      charset: this.sequelize.dialect.name === 'mysql' ? 'utf8' : null,
+      collate: this.sequelize.dialect.name === 'mysql' ? 'utf8_unicode_ci' : null
     });
   }
   /**
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by WikiRik** [comment]
See #612 for earlier discussion about this

**Comment by QuentinFarizon** [comment]
@WikiRik What do you think of my solution ? 

With something like :
```
const charsetableDialects = ['mysql', 'mariadb', 'snowflake']
(...)
charset: charsetableDialects.includes(this.sequelize.dialect.name) ? 'utf8' : null,
collate: charsetableDialects.includes(this.sequelize.dialect.name) ? 'utf8_unicode_ci' : null
```

**Comment by WikiRik** [comment]
That looks good

**Comment by QuentinFarizon** [comment]
@WikiRik I've pushed a PR : https://github.com/sequelize/umzug/pull/624

**Comment by qfarizon-qftech** [comment]
@WikiRik It would be great to update sequelize-cli to use this new version !

**Comment by WikiRik** [comment]
@qfarizon-qftech sequelize-cli is not meant tested with or updated for the v7 alphas and still uses umzug v2. The new CLI, which we started work on in the sequelize monorepo (and will be published as `@sequelize/cli`), will be using umzug v3 with this update.

**Comment by qfarizon-qftech** [comment]
@WikiRik Can I test @sequelize/cli as of today ?

**Comment by qfarizon-qftech** [comment]
For now I have patched umzug@2 using patch-package.

**Comment by qfarizon-qftech** [comment]
For now I have patched umzug@2 using patch-package.

**Comment by mmkal** [comment]
If anyone would like to backport anything to v2.x I'm fine to review a pull request and publish, just open it against v2.x branch. I won't check it beyond just building and publishing though.
