### ISSUE TITLE
Update `type-fest` to `^4.10.2` to ensure compatibility with TypeScript 5.4

### ISSUE THREAD

**Issue by voxpelli** [sequelize/umzug#645]
See the release notes: https://github.com/sindresorhus/type-fest/releases/tag/v4.10.2

And https://github.com/sindresorhus/type-fest/pull/807 that's mentioned within them

/ Sincerely co-maintainer of `type-fest` and user of `umzug`

**Comment by mmkal** [comment]
Merged. Will aim to publish today.
