### ISSUE TITLE
Officially supported sequelize versions

### ISSUE THREAD

**Issue by jukkah** [sequelize/umzug#73]
The latest release of sequelize is `v3.21.0` and we are still officially supporting (in .travis.yml) only `v.1.7.10`, `v2.0.0-rc8` and `v2.0.0`. Should we add official support for newer versions? It shouldn't be a huge task because at the moment of writing #69 I ran tests against almost all the sequelize versions without any other issues.

I vote for officially supported versions:

- `^1.0.0` := latest < `v2.0.0`, currently `v1.7.9`.
- `^2.0.0` := latest < `v3.0.0`, currently `v2.1.3`.
- `^3.0.0` := latest < `v4.0.0`, currently `v3.21.0`.

**Comment by sdepold** [comment]
I'd like to support every major version if possible.

**Comment by jukkah** [comment]
In addition, LTS of Node.js v0.10 is ending on [2016-10-01](https://github.com/nodejs/LTS). Should we add official support for newer LTS versions before that?

**Comment by jukkah** [comment]
I [studeied](https://travis-ci.org/jukkah/umzug/builds/123908278) both Sequelize  and Node.js versions. The result is that umzug works well with all version combinations, but there is some kind of build problem with sqlite on iojs-v3.
