### ISSUE TITLE
Allow to pass storage object to Umzug constructor

### ISSUE THREAD

**Issue by koistya** [sequelize/umzug#77]
``` js
class Storage {
  constructor() { ... }
  logMigration() { ... }
  unlogMigration() { ... }
  executed() { ... }
}

const umzug = new Umzug({ storage: Storage });
```

**Comment by jukkah** [comment]
Hmm... Why not? :+1: Pull request is more than welcome!

**Comment by randomstuff** [comment]
Is it useful to pass the storage class instead of the storage instance? I'd want to do that instead:

    const umzug = new Umzug({ storage: new Storage() });
