### ISSUE TITLE
Is there a way to programmatically define migrations?

### ISSUE THREAD

**Issue by techwraith** [sequelize/umzug#79]
I'd like to generate migration up and down functions programmatically (without writing to the file system) is there a way to do that?

**Comment by jukkah** [comment]
I'm not 100% sure what you mean. Do you mean
```javascript
let migration = {
  up(...) { ... },
  down(...) { ... }
};
umzug.execute({ migrations: [migration], method: 'up' });
```
instead of
```javascript
umzug.execute({ migrations: ['migration1.js'], method: 'up' });
```
? This is not currently possible but pull request is more than welcome.

**Comment by hackhat** [comment]
Any news on this? 

My code is in typescript, therefore migrations are in typescript as well. Is there anyway to pass the migrations as an object instead of providing the folder for umzug to lookup?

**Comment by jedwards1211** [comment]
@Techwraith as a result of https://github.com/sequelize/umzug/pull/164 it is possible to pass an array of `Migration` class instances in `options.migrations`.

**Comment by hackhat** [comment]
Update: If anyone is interested in how I fixed... is I build my own migration runner in plain typescript.

**Comment by wildcookie007** [comment]
> Update: If anyone is interested in how I fixed... is I build my own migration runner in plain typescript.

Would you please share your solution?

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/umzug/pull/199 introduces helper which can be used to build migrations array
