### ISSUE TITLE
Warning: a promise was created in a handler but was not returned from it

### ISSUE THREAD

**Issue by bradleygore** [sequelize/umzug#81]
I've started a new project and am using postgres and sequelize, and umzug for migrations. My migrations are working, as in the tables are created, fields and constraints correct, etc... but I'm continuously getting this error:
Warning: a promise was created in a handler but was not returned from it

My migrations look like this (note, I've used both es6 and es5 syntax with no difference):

```js
//######-someSchema.js
module.exports = {
  up: (queryInterface, DataTypes) => {
    return queryInterface.createTable(......)
        .then(() => queryInterface.createTable('some_table_with_fk_to_first_table', .....);

    //ES5 syntax, no difference:
    return queryInterface.createTable(...)
        .then(function() { 
            return queryInterface.createTable(...);
        });
  }, 
  down: (queryInterface, DataTypes) => {
  
  }
};
```

and here's where I'm invoking umzug from (again, it's technically working but this error is obnoxious and I want to make sure it's not something I should be worried about...)

```js
//migrations.js
umzug.pending()
    .then(pendingMigrations => {
        console.log('pendingMigrations: ', pendingMigrations.map(p => p.file));
        umzug.up()
            .then(() => console.log('Migrations Done'))
            .catch(err => {
                console.log('MIGRATION ERROR!', arguments);
                //umzug.down() TODO: How to only run .down of failed migration?
            });
    })
    .catch(err => console.log('Error getting pending migrations: ', err));
```

As you may see, I also have a secondary question in the `umzug.up().catch(...)` handler - "How to run the "down" method of failed migration" - if any insight on this also, would appreciate it!

**Comment by mickhansen** [comment]
Your second example is not using return at all.

**Comment by jukkah** [comment]
> **Warning: a promise was created in a handler but was not returned from it**
> This usually means that you simply forgot a return statement somewhere which will cause a runaway promise that is not connected to any promise chain. ([Bluebird documentation](http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-was-not-returned-from-it))

I can't see the root cause in your migration file. Instead there should be `return umzug.up()` in your `migrations.js`. I expect that's what @mickhansen already said.

> How to run the "down" method of failed migration

My opinion is that if any method fails, it should not have any side effects.The right way is to wrap your SQL commands into a transaction and commit/rollback it at the end of `up`. (Umzug is not wrapping commands into transactions.)

**Comment by bradleygore** [comment]
Ok, thanks @mickhansen and @jukkah - it certainly wasn't apparent from the docs that the initial `umzug.someMethod()` call needed a return. In fact, this is  how the docs show it being used:
```
var Umzug = require('umzug');
var umzug = new Umzug({});

umzug.someMethod().then(function (result) {
  // do something with the result
});
```
I'm just using `node ./path/to/migrations.js` to kick off the migration, so just followed the example as it is.

@jukkah So you're recommending not to use the `down` methods at all then, right? That makes sense to just wrap it into a transaction. Am I understanding right that this means each migration file's `up` method will have its own transaction, or is there a way to make all migrations roll up into a single transaction?

Again - the help is appreciated :smile:

**Comment by jukkah** [comment]
@bradleygore Yeah, that's how promises work. Maybe we should point out that umzug is __completely__ async library.

```js
up(...) {
  // 1. begin transaction
  // 2. migrate db from state {n} to state {n + 1}
  // 3a. commit if all passed
  // 3b. rollback if something went wrong
  // 4. end transaction
}

down(...) {
  // 1. begin transaction
  // 2. migrate db from state {n + 1} to state {n}
  // 3a. commit if all passed
  // 3b. rollback if something went wrong
  // 4. end transaction
}
```

You got the point. Above are the procedures I meant.

**Comment by bradleygore** [comment]
@jukkah ok, awesome - this makes sense. Thanks again!
