### ISSUE TITLE
How to add a field to a model without affecting data

### ISSUE THREAD

**Issue by KumarHX** [sequelize/umzug#83]
Hey guys,

I am trying to understand how to add fields to a created table using this library. Could someone please post an example? Say I want to add a field to this model:

var Services = sequelize.define("Services", {
    service_type : {type: Sequelize.STRING},
    service_name : {type: Sequelize.STRING, primaryKey: true, allowNull: false}
});

how would I go about doing it?

**Comment by jukkah** [comment]
This is a [sequelize](https://github.com/sequelize/sequelize) specific question as you are using sequelize's `queryInterface` within your migration. Please read [sequelize documentation](http://docs.sequelizejs.com/en/latest/docs/migrations/#addcolumntablename-attributename-datatypeoroptions-options) to see how to add columns into tables.

**Comment by AlexKhodaverdian** [comment]
I'm working with Kumar currently. Isn't queryInterface only used for CLI migrations (Not for prod migrations?). Also what happens to all the current data when such a migration occurs?

**Comment by jukkah** [comment]
> Isn't queryInterface only used for CLI migrations (Not for prod migrations?).

I'm assuming CLI means [sequelize/cli](https://github.com/sequelize/cli)? It will pass sequelize's queryInterface as a parameter to your migrations [here](https://github.com/sequelize/cli/blob/477900c134fbeb0ceac2bcb9774736bf7efc4bf1/lib/tasks/db.js#L355). If you run migrations in your local machine with cli why to not run them with the cli in production too?

> [W]hat happens to all the current data when such a migration occurs?

It depends on what DDL statements you perform within your migration. If you call `queryInterface.addColumn(...)` on a model it would execute `ALTER TABLE ... ADD ...` and no data will be lost as nothing has been removed. If you call `queryInterface.removeColumn(...)` on a model it would execute `ALTER TABLE ... DROP ...` and data of that removed column will be lost. You can also perform DML statements to migrate data. Guys at sequelize/sequelize will help you if you don't know how to use sequelize's queryInterface.

**Comment by jukkah** [comment]
An example migration you asked (untested):

```js
module.exports = {
  up: function(queryInterface, Sequelize) {
    queryInterface.addColumn('Services', 'service_price', Sequelize.DECIMAL);
  },
  
  down: function(queryInterface, Sequelize) {
    queryInterface.removeColumn('Services', 'service_price');
  }
};
```

**Comment by sdepold** [comment]
You will need to return the promise from the migrations though.

**Comment by AlexKhodaverdian** [comment]
So in my code, do I just add this in my Services file?

```
module.exports = {
  up: function(queryInterface, Sequelize) {
    return queryInterface.addColumn('Services', 'service_price', Sequelize.DECIMAL);
  },
};
```
to add a column?

What else do I need to do, as this doesn't seem to work alone. Do I need to use umzug? Sorry again. I'm not using CLI as I need to deploy on heroku.

**Comment by jukkah** [comment]
I haven't used Heroku yet but I guess you want to run migrations on deploy. If you deploy small and often, I guess Sequelize.sync() is smart enough, and you don't need umzug and migrations at all. But if you decide to use migrations, the easiest way is to use sequelize-cli. When you have some migration files in place then you need to run `sequelize db:migrate` to execute them.

**Comment by jukkah** [comment]
I'm closing this now for period of inactivity. Feel free to reopen or comment this issue (even if closed).
