### ISSUE TITLE
SequelizeMeta table is created with THREE indexes (for a single field)

### ISSUE THREAD

**Issue by iamjochem** [sequelize/umzug#87]
hi there,

I just ran `sequelize-cli@2.4.0` (with `sequelize@3.23.3`) against a new database and got a [MySQL] table that has the following schema: 

```sql
CREATE TABLE `sequelize_meta` (
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE KEY `name` (`name`),
  UNIQUE KEY `sequelize_meta_name_unique` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```

> I guess that this is probably a `sequelize` issue rather than `sequelize-cli` based on [this line of code](https://github.com/sequelize/umzug/blob/a94a740502769c8f6fd2e4812471f4dcb2c63986/lib/storages/sequelize.js#L103)

creating three indexes where one will do is rather wasteful, in the case of the **SequelizeMeta** the extraneous indexes are not a practical problem because the number of records stored is, from a RDMS point-of-view, minimal. still, it looks messy (IMO).

If this is what `sequelize`'s `Model.sync` method does then that seems to me to be problematic - it's rather inefficient to create/maintain these duplicate indexes - at the very least `Model.sync` should be documented as having caveats, no? 

This issue seems, to me, to tie in with the whole "should-I-use-model.sync-or-migrations" question ... one that I personally find a little confusing (okay that is a lie, I'm quite adamant that `model.sync` should be avoided like the plague and [single-query] migrations should be used, but that is just my opinion!) ... the [sequelize] documentation show 2 distinct methods of tackling schema creation/mutation but does offer any guidance about why you should use one or the other, additionally it's not immediately clear that the 2 methods are (AFAICT) mutually exclusive.

**Comment by jukkah** [comment]
I double checked our Sequelize integration (a.k.a. sequelize_meta, Sequelize storage), and it's using Sequelize correctly. I think this is an issue of Sequelize. :football: → @sdepold

**Comment by jukkah** [comment]
> ```sql
> UNIQUE KEY `name` (`name`),
> UNIQUE KEY `sequelize_meta_name_unique` (`name`)
> ```

@durango @felixfbecker @janmeier @mickhansen @sdepold @sushantdhiman This is an issue of sequelize (or either sequelize-cli).

In addition, there should actually be some docs about when to use sync and when to use migrations. Even migrations are commonly known by programmers, it is not always clear when it is wise to use sync.
