### ISSUE TITLE
How to listen for migration events

### ISSUE THREAD

**Issue by andela-echigbo** [sequelize/umzug#97]
Hello, Guys. 

I know this is not really an issue, but I have asked [this](http://stackoverflow.com/questions/40214435/how-to-listen-for-sequlizejs-migration-events) on Stackoverflow but answer yet for over 13 hours

You know when you use **SequelizeJS** with _migration_ and not `.sync`, when you want to make changes to your DB structure, you generate and edit a migration for it. 
Then you run `sequelize db:migrate`
This updates the db schema structure but not the corresponding Sequelize model.
You have to manually edit the model to match the current state of the actual DB

Now that is what I want to automate (kind of).
There is a function in Sequelize QueryInterface: `showAllTables` and `describeTable` that list all tables in the database and get table schema respectively.

I want to use those functions to fetch the current database schema and populate it to a file each time I run `sequelize db:migrate` or `sequlize db:migrate:undo` (Just like _rails migration_ does)

Now my problem is hooking into that migration event.

I know that Sequlize CLI use **Umzug** for migration and the Umzug README says:

>Umzug is an EventEmitter. Each of the following events will be called with name, migration as arguments. Events are a convenient place to implement application-specific logic that must run around each migration:

> - migrating - A migration is about to be executed.  
> - migrated - A migration has successfully been executed.  
> - reverting - A migration is about to be reverted.  
> - reverted - A migration has successfully been reverted.  

How do I hook in and listen for those events with my current Sequelize object and perform actions when the event happens?

Thanks

**Comment by jukkah** [comment]
I'm afraid CLI doesn't support Umzug events right now. The only way is to directly listen Umzug instance:

```js
const umzug = new Umzug(...);
umzug.on('migrating', (...) => { ... });
```

**Comment by andela-echigbo** [comment]
Thanks @jukkah for your response. I actually tried that by what I got in the `umzug` test file.
I think my problem was the file I placed it. I will try that now and get back to you on my progress.

Thank you.

**Comment by andela-echigbo** [comment]
@jukkah; I was not able to get it to work. I tried putting the script in the `.sequlizerc` and event in the migration file itself, but the event doesn't seem to be observed. I guess it's like you said, CLI doesn't support the Umzug events now.

Thanks for the help anyways.

**Comment by jukkah** [comment]
There is an another **hack**! You can add code into up/down functions of migration file. So your migration files could look like this:

```js
const listener = require('../my-listener-hack');

module.exports = {
  up(...) {
    // on migrating
    listener.doSomethingOnMigrating();

    // migrate your DB here

    // on migrated
    listener.doSomethingOnMigrated();
  },
  down(...) { ... }
};
```

**Comment by andela-echigbo** [comment]
Thank you @jukkah 
Given the new version of CLI just returns a `queryInterface` method I couldn't do it exactly like that as anything after the return wouldn't execute.

However, since the returned methods are promises, I could chain a `then` method and pass my function to it. It then runs that function after migrating.

```javascript
const updateSchema = require('../update_schema');

module.exports = {
  up: function (queryInterface, Sequelize) {
    return queryInterface.createTable('users', {
      // fields definition
    }, {
      underscored: true
    }).then(updateSchema);
  },
  down: function (queryInterface, Sequelize) {
    return queryInterface.dropTable('users').then(updateSchema);
  }
};
```
My only concern with this is that I will have to chain the `.then(updateSchema)` to any migration function I write. But it's the best solution I have so far.

Thanks again.

**Comment by jukkah** [comment]
Yeah, this is an ugly hack but it's working. :sweat_smile:

I'm closing the issue for now. Reopen it or open a new issue if needed.
